### ISSUE TITLE
select video only

### ISSUE THREAD

**Issue by antoinefotso** [baronha/react-native-multiple-image-picker#1]
Thanks for this awesome library ,
 Is there anyway to select only videos ?
I also have empty array result when i set singleSelectedMode to true

**Comment by baronha** [comment]
> Thanks for this awesome library ,
> Is there anyway to select only videos ?
> I also have empty array result when i set singleSelectedMode to true

I say YES. of course. Please check the [new version(0.1.2)](https://github.com/baronha/react-native-multiple-image-picker#whats-new-012). Enjoy my library.
Thanks for your comments for this library

**Comment by hpsurekha** [comment]
Hi, thank you for the library.
when I set `mediaType: "video"` it's not showing video from gallery.
I have two videos in the download folder where images are stored
one video with .mov and .mp4 file type, but none of them is getting shown.
below are my options when opening picker view, working fine for image selection but not showing video when `mediaType: 'video'` or `mediaType: 'all'`. I don't want image and video together, was just trying to check, whether video is showing or not in `'all'` option.

```
mediaType: 'video',
isExportThumbnail: false,
usedCameraButton: false,
singleSelectedMode: true,
```
PS: Please update me if I am passing any wrong option here.
Thank you.

**Comment by baronha** [comment]
> 

You can check ```maxVideoDuration``` option. Default 60 (60 seconds).  Only show videos under 60 seconds in the gallery.
