### ISSUE TITLE
Android - App không tắt Crop Controller khi isCrop bằng false

### ISSUE THREAD

**Issue by hieuphan1030** [baronha/react-native-multiple-image-picker#101]
Hi bạn,
Hiện mình đang sử dụng lib của bạn. Lib thật sự rất tốt nhưng mà khi mình bật enable Crop  cho avatar thì hoạt động tốt bình thường, nhưng khi mình chuyển qua multi select image và mình đã set ` isCrop = false & singleSelectedMode = false` nhưng mà nó không hoạt động,  tất cả bức hình mình chọn đều phải crop. Nếu tắt app đi bật lại thì nó không còn bị.

Nó hoạt động tốt trên ios

Bạn có thể cho mình hướng để xử lý đc ko ạ? Cảm ơn bạn rất nhiều!!!

**Comment by hieuphan1030** [comment]
hi @baronha bạn có cách nào fix issue này không?
mình cảm ơn!

**Comment by hieuphan1030** [comment]
Hi @baronha ,Nếu mà bạn thêm Optional cleanup thì có giải quyết dc nó không nhỉ?

**Comment by fukemy** [comment]
bạn thử vào thẳng lib tìm cái condition mà sửa xem.

**Comment by denisbevilacqua** [comment]
same issue here!

**Comment by denisbevilacqua** [comment]
Fixed on `1.0.1`!

**Comment by baronha** [comment]
> Fixed on `1.0.1`! @baronha @hieuphan1030

Thank you for your contribution @denisbevilacqua 🫡🫡🫡
