### ISSUE TITLE
Unable to Open Gallery on iOS and Android

### ISSUE THREAD

**Issue by outranker** [baronha/react-native-multiple-image-picker#102]
**Description**:
I am currently experiencing an issue with the this library where I am unable to open the gallery on both iOS and Android platforms. I have followed the installation instructions provided in the library's documentation, but the gallery does not open when calling the `openPicker` method.

**Steps to Reproduce**:
1. Install and link the this library according to the documentation.
2. Add the necessary permissions for accessing the photo library in the `AndroidManifest.xml` file and the `Info.plist` file.
3. Call the `openPicker` method to open the gallery and select images.

**Expected Behavior**:
I expect the gallery to open on both iOS and Android platforms when calling the `openPicker` method. I should be able to select multiple images from the gallery.

**Actual Behavior**:
The gallery does not open on either iOS or Android. No error messages or warnings are displayed in the console logs. The `openPicker` method seems to have no effect.

**Environment**:
- React Native version: 0.64.1
- `@baronha/react-native-multiple-image-picker` version: 1.0.0
- Platform(s) experiencing the issue: iOS, Android
- Device/emulator/simulator: [iPhone X, Galaxy S20, iOS Simulator iPhone 12]

**Additional Information**:
- I have confirmed that the necessary permissions are granted for accessing the photo library on both iOS and Android.
- I have tested with the latest versions of React Native and `@baronha/react-native-multiple-image-picker`, but the issue persists.

This is how i import and use this library:
```
import ImagePicker, {
  Results,
  MediaType,
} from '@baronha/react-native-multiple-image-picker';
```

```
const chooseImage = async () => {
    try {
      const res = await ImagePicker.openPicker<MediaType.IMAGE>({
        mediaType: MediaType.IMAGE,
        isExportThumbnail: true,
        maxSelectedAssets: 10,
        selectedAssets: images,
      });
    } catch (error) {
      console.log(error);
    }
    addImages(res);
  };
  ```
```
...
<TouchableOpacity onPress={chooseImage}>
  Add Images
</TouchableOpacity>
...
```

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you!

---

**Comment by outranker** [comment]
as an additional info this is what error in the catch block looks like:
```
[TypeError: undefined is not an object (evaluating '_reactNativeMultipleImagePicker.default.openPicker')]
```

**Comment by JeongSeongWu** [comment]
I'm also having a similar problem. here is my code
`import MultipleImagePicker from '@baronha/react-native-multiple-image-picker';
const response = await MultipleImagePicker.openPicker(options);
`

but I got this error ...
TypeError: Cannot read property 'openPicker' of undefined

Please let me know, How can I fix it?

**Comment by outranker** [comment]
@JeongSeongWu Looks like they didn't update the types for this version. You can patch the types yourself for now just to make Typescript happy. For that you need to create a .d.ts file such as types.d.ts (preferably at the root of your project) and declare a module like below:
```
declare module "socket.io" {
  type openPicker = () => void;
}
```

You will also need to provide function types as well. Let me know if it works

**Comment by JeongSeongWu** [comment]
![image](https://github.com/baronha/react-native-multiple-image-picker/assets/87528753/4c40b22f-186c-42a9-9c35-e79342c20bf4)
Am I right? I still get error...;;
And how does this relate to socket.io?
Is this library based on soket.io?
Even if my question is strange, I hope you understand.

**Comment by outranker** [comment]
@JeongSeongWu Oh I am sorry, I just copy pasted the code from somewhere and forgot to modify the module name. In the place of 'socket.io' you should write the name of the package which is 'baronha@react-native-multiple-image-picker'

**Comment by JeongSeongWu** [comment]
I changed the module name but I keep getting the error... T^T

**Comment by outranker** [comment]
@JeongSeongWu is it still the same error?
That's weird. I just tried it and the TS error disappeared since I manually created the types for the module

![Screenshot 2023-05-24 at 8 44 05 AM](https://github.com/baronha/react-native-multiple-image-picker/assets/20103472/76ea4313-3390-440c-b1c7-7b380004441e)
![Screenshot 2023-05-24 at 8 44 15 AM](https://github.com/baronha/react-native-multiple-image-picker/assets/20103472/9f2838cf-d60f-4cfc-9f09-dc1d11781e4c)

**Comment by outranker** [comment]
@JeongSeongWu Oh I see now! My apologies for the confusion. It seems the late-night coding session got the best of me. Let's blame it on a case of "midnight gremlins" wreaking havoc on my typing skills.

Without further ado, below is the corrected package name which should hopefully fix the TS error:

```javascript
declare module '@baronha/react-native-multiple-image-picker' {...}
```

With this fix, let's squash those pesky bugs and bring back smooth sailing to your code.

btw, don't forget that this only makes the TS error go away

**Comment by JeongSeongWu** [comment]
![image](https://github.com/baronha/react-native-multiple-image-picker/assets/87528753/32c03e5f-0075-47ca-bef3-18302ca4bf6f)
I am sorry for the late reply.
I changed it as above, but the existing error has been changed to another error.
![image](https://github.com/baronha/react-native-multiple-image-picker/assets/87528753/cb7e8f7b-0800-4672-9b0c-cdaf010e7813)

**Comment by hieuphan1030** [comment]
Hi @JeongSeongWu, @outranker   You can fixed the code like below.
```
import {
  // @ts-ignore
  openPicker,
} from '@baronha/react-native-multiple-image-picker'
```

```
const onPicker = async () => {
    try {
      const singleSelectedMode = true;

      const response = await openPicker({
        selectedAssets: images,
        isExportThumbnail: true,
        maxVideo: 1,
        doneTitle: 'Xong',
        singleSelectedMode,
      });
   
     setImages(response);
    } catch (e) {}
}
  ```

**Comment by phuoctai12t** [comment]
You can use patch-package to declare type defination for openPicker and remove error of export default
`diff --git a/node_modules/@baronha/react-native-multiple-image-picker/src/index.d.ts b/node_modules/@baronha/react-native-multiple-image-picker/src/index.d.ts
index f8ec0d3..a25206c 100644
--- a/node_modules/@baronha/react-native-multiple-image-picker/src/index.d.ts
+++ b/node_modules/@baronha/react-native-multiple-image-picker/src/index.d.ts
@@ -102,6 +102,4 @@ type MultipleImagePickerType = {
   ): Promise<MediaTypeResults[T]>;
 };
 
-const { MultipleImagePicker } = NativeModules;
-
-export default MultipleImagePicker as MultipleImagePickerType;
+export const openPicker: MultipleImagePickerType['openPicker'];
`

**Comment by MachuKP** [comment]
@outranker make sure you add privacy description for Photo Library, Microphone and Camera usage

**Comment by Martyneris** [comment]
I have the same issue, `MultipleImagePicker.openPicker` does nothing, the gallery doesn't open.

Environment:

React Native version: 0.64.2
@baronha/react-native-multiple-image-picker version: 0.2.9
Platform(s) experiencing the issue:  Android
Device/emulator/simulator: [Samsung Galaxy A04s]

I have also tried updating @baronha/react-native-multiple-image-picker to its latest version, that also didn't help.

**Comment by baronha** [comment]
You can upgrade to the new version (1.1.2):

```js
import { openPicker } from '@baronha/react-native-multiple-image-picker';
// ...
const response = await openPicker(options);
```

**Comment by Martyneris** [comment]
I have tried upgrading to 1.1.2 and importing like in your example.
<img width="904" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/33836575/8944893a-4e4c-4b4a-b221-bfbe91282758">
Can not use the openPicker

**Comment by baronha** [comment]
> I have tried upgrading to 1.1.2 and importing like in your example. import: <img alt="image" width="891" src="https://user-images.githubusercontent.com/33836575/271493085-c2e524b5-59a7-4a03-b446-e851c79b1b0e.png"> usage: <img alt="image" width="904" src="https://user-images.githubusercontent.com/33836575/271492918-8944893a-4e4c-4b4a-b221-bfbe91282758.png"> Can not use the openPicker

Oh, my fault. I just released a new version 1.1.3 to fix this error.

**Comment by Martyneris** [comment]
Thanks, 1.1.3 solved the import/type problem. 
Although now I am getting this error, when using openPicker like from your example: 

`TypeError: Cannot read properties of undefined (reading 'IMAGE')
    at openGallery$`

**Comment by shahbazmancho** [comment]
Any update here ?  i am facing runtime error 

` LOG  [TypeError: Cannot read property 'IMAGE' of undefined]`
