### ISSUE TITLE
.Dng files are not showing

### ISSUE THREAD

**Issue by nb-immosnapp** [baronha/react-native-multiple-image-picker#103]
the new raw fomat (.dng) are not supported (image taken from iphone 14 pro max)
<img width="331" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/114584968/cb8ef601-c4d3-4a81-b4b5-1e78aec76151">

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
