### ISSUE TITLE
Ứng dụng bị từ chối trên google play vì chứa quyền MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by hm1061998** [baronha/react-native-multiple-image-picker#105]
hi anh, em có sử dụng thư viện của anh phiên bản 1.0.0
có vẻ thư viện này đang tự động thêm các quyền MANAGE_EXTERNAL_STORAGE . mặc dù em không hề thêm nó vào.
ứng dụng của em đang bị google từ chối vì chứa quyền này, em không làm cách nào xoá nó đi được

**Comment by hieuphan1030** [comment]
Hi @hm1061998 ,  mình cũng gặp vấn đề giống bạn, đây là cách mình fix nó

![image](https://github.com/baronha/react-native-multiple-image-picker/assets/108206954/bdc6aabe-fdbf-4c59-9b6c-c17e921a614b)

bạn vào libs rồi vào file AndroidManifest, sau đó bạn remove dòng
 ` <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`
 
 sau đó bạn dùng lệnh  (để lưu lại thay đổi)
`npx patch-package@baronha/react-native-multiple-image-picker --use-yarn`

chúc bạn thành công!

**Comment by hm1061998** [comment]
@hieuphan1030 cảm ơn bạn ❤

**Comment by baronha** [comment]
> Hi @hm1061998 , mình cũng gặp vấn đề giống bạn, đây là cách mình fix nó
> 
> ![image](https://user-images.githubusercontent.com/108206954/243338680-bdc6aabe-fdbf-4c59-9b6c-c17e921a614b.png)
> 
> bạn vào libs rồi vào file AndroidManifest, sau đó bạn remove dòng ` <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`
> 
> sau đó bạn dùng lệnh (để lưu lại thay đổi) `npx patch-package @baronha/react-native-multiple-image-picker --use-yarn`
> 
> chúc bạn thành công!

Bạn có thể tạo pull request cho mình để mình cập nhập lại thư viện nhé.
Cám ơn vì bạn đã hỗ trợ cộng đồng ✨
