### ISSUE TITLE
      > Could not resolve com.android.tools.build:gradle:4.1.1.

### ISSUE THREAD

**Issue by 2741147837** [baronha/react-native-multiple-image-picker#106]
yarn install
yarn android
然后报错
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':baronha_react-native-multiple-image-picker'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':baronha_react-native-multiple-image-picker:classpath'.
      > Could not resolve com.android.tools.build:gradle:7.1.1.
        Required by:
            project :baronha_react-native-multiple-image-picker
         > Could not resolve com.android.tools.build:gradle:7.1.1.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.1.1/gradle-7.1.1.pom'.
                  > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5.1/userguide/build_environment.html#gradle_system_properties
                     > Remote host terminated the handshake

**Comment by baronha** [comment]
try upgrade to new version [1.1.2](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/1.1.2)
