### ISSUE TITLE
[Bug] [Android] [Crash] - App crashes when pressing done in preview page 

### ISSUE THREAD

**Issue by itsnyx** [baronha/react-native-multiple-image-picker#107]
Hello, have nice day.

app crashes when you press done at preview page of a selected asset in both video or image mode.
the done button should be disabled as no asset is selected which is disabled on the main screen as in following picture: 

![image](https://github.com/baronha/react-native-multiple-image-picker/assets/74738973/8af159d4-f0da-429a-af52-f16d5e5af555)

but when i preview the item the done button is no longer disabled :

![image](https://github.com/baronha/react-native-multiple-image-picker/assets/74738973/eb95ff36-c98c-4cde-9e7c-0881bc0cbfe3)

and if you press on the done here without selecting the image app crashes ! (this problem happens in real device (both debug and production build ) but somehow its ok in android emulator! )

**Comment by itsnyx** [comment]
hey @baronha how are you doing?
any update on this?!

**Comment by baronha** [comment]
> hey @baronha how are you doing? any update on this?!

I will fix this problem soon in the next 2-3 days

**Comment by itsnyx** [comment]
@baronha  hello, hope you doing well , any updates on this ?

**Comment by baronha** [comment]
Sincere apologies for the delay but I can't reproduce your error at all.

https://github.com/baronha/react-native-multiple-image-picker/assets/23580920/6d5b5559-5b48-48ce-a3de-9e4afcf8da83

**Comment by itsnyx** [comment]
@baronha this error happens on real android device. 
it works fine with emulator but not on real android device 

i also tested both debug and build and both crashes on real device.

**Comment by sarafhbk** [comment]
Same here any solution?  @baronha

**Comment by itsnyx** [comment]
@sarafhbk you can set isPreview to false in order to bypass this bug!

**Comment by jackgardner-mudbath** [comment]
> @sarafhbk you can set isPreview to false in order to bypass this bug!

Can confirm, setting `isPreview` to false resolves this. The user can still preview their image but pressing the bottom left corner

**Comment by hhy123540** [comment]
> > @sarafhbk您可以将 isPreview 设置为 false 以绕过此错误！
> 
> 可以确认，设置`isPreview`为 false 可以解决此问题。用户仍然可以通过按左下角预览图像
Hello, I also have this problem. Have you solved it

**Comment by hhy123540** [comment]
@baronha Did the author solve this problem

**Comment by baronha** [comment]
Try upgrade [v.1.0.2](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/1.0.2)
