### ISSUE TITLE
 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bitmap?

### ISSUE THREAD

**Issue by ymane** [baronha/react-native-multiple-image-picker#11]
Null safe error for android  compileSdkVersion = 30 and targetSdkVersion = 30
`node_modules\@baronha\react-native-multiple-image-picker\android\src\main\java\com\reactnativemultipleimagepicker\MultipleImagePickerModule.kt: (221, 18): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bitmap?`

Thanks for support

**Comment by baronha** [comment]
I will try to check in ```SdkVersion = 30```. 
Does it work in ```SdkVersion =  29```?

**Comment by ymane** [comment]
Yes working for SdkVersion = 29

**Comment by tushar04** [comment]
@baronha Could you please review and merge the pull request from @ymane.

**Comment by baronha** [comment]
> @baronha Could you please review and merge the pull request from @ymane.

I'm merged. Thanks, @ymane, and @tushar04.

**Comment by ymane** [comment]
@baronha  Thanks for merge
