### ISSUE TITLE
ios: Not callback permission on ios when user deny

### ISSUE THREAD

**Issue by hieuphan1030** [baronha/react-native-multiple-image-picker#110]
Mình đang bị vấn đề khi người dùng từ chối quyền truy cập ảnh, sau khi tắt vào lại trên ios thì nó không gọi lại quyền truy cập nữa.
Có cách nào khắc phục không @baronha ?
thank you!

**Comment by baronha** [comment]
> Mình đang bị vấn đề khi người dùng từ chối quyền truy cập ảnh, sau khi tắt vào lại trên ios thì nó không gọi lại quyền truy cập nữa. Có cách nào khắc phục không @baronha ? thank you!

Cách mình dùng permission cho mọi project là sử dụng [react-native-permissions](https://github.com/zoontek/react-native-permissions) trước khi gọi `func openPicker()`. Mình cũng có [roadmap](https://github.com/baronha/react-native-multiple-image-picker#to-do) dành cho phần permission nhưng vẫn chưa có thời gian handle nó
