### ISSUE TITLE
can't change photos selection iOS

### ISSUE THREAD

**Issue by jzafar** [baronha/react-native-multiple-image-picker#112]
I am using v 1.0.0. i have allowed all photos in permissions. but when i openPicker it only shows recent added and even i can't change selection. Am i missing something?
![IMG_9428](https://github.com/baronha/react-native-multiple-image-picker/assets/2162704/e165c531-bff6-4ef8-befb-ecb9d92b4f40)

**Comment by baronha** [comment]
Try upgrading to the latest version ver.1.1.2

**Comment by jzafar** [comment]
After updating still same issue. it seems package is crashing because of updating UI from background thread. May be this will help
Main Thread Checker: UI API called on a background thread: -[UIViewController initWithNibName:bundle:]
PID: 1389, TID: 357408, Thread name: (none), Queue name: com.apple.photos.accessCallbacks, QoS: 0
Backtrace:
4   RentSpace                           0x0000000105b71390 $s13TLPhotoPicker08TLPhotosB14ViewControllerCACycfc + 2240
5   RentSpace                           0x0000000105b713ec $s13TLPhotoPicker08TLPhotosB14ViewControllerCACycfcTo + 20
6   RentSpace                           0x000000010658e9e8 $s34react_native_multiple_image_picker31CustomPhotoPickerViewControllerCACycfc + 160
7   RentSpace                           0x000000010658ea28 $s34react_native_multiple_image_picker31CustomPhotoPickerViewControllerCACycfcTo + 20
8   RentSpace                           0x000000010658e940 $s34react_native_multiple_image_picker31CustomPhotoPickerViewControllerCACycfC + 28
9   RentSpace                           0x000000010659b72c $s34react_native_multiple_image_picker19MultipleImagePickerC08navigateH0yyF + 288
10  RentSpace                           0x000000010659a9c4 $s34react_native_multiple_image_picker19MultipleImagePickerC04openH07options7resolve6rejectySo12NSDictionaryC_yypSgcySSSg_AKs5Error_pSgtctFySo21PHAuthorizationStatusVcfU_ + 160
11  RentSpace                           0x0000000105b734f8 $sSo21PHAuthorizationStatusVIegy_ABIeyBy_TR + 56
12  Photos                              0x00000001ae90f64c C4CCA50E-E935-3716-9794-836EDC0C671B + 1115724
13  PhotoLibraryServicesCore            0x00000001af289bb4 882FCD45-F394-3368-814F-D720CD3D88EA + 27572
14  libdispatch.dylib                   0x000000010da58520 _dispatch_call_block_and_release + 32
15  libdispatch.dylib                   0x000000010da5a038 _dispatch_client_callout + 20
16  libdispatch.dylib                   0x000000010da620b0 _dispatch_lane_serial_drain + 984
17  libdispatch.dylib                   0x000000010da62e28 _dispatch_lane_invoke + 464
18  libdispatch.dylib                   0x000000010da6fc74 _dispatch_workloop_worker_thread + 736
19  libsystem_pthread.dylib             0x00000001f979dddc _pthread_wqthread + 288
20  libsystem_pthread.dylib             0x00000001f979db7c start_wqthread + 8
