### ISSUE TITLE
Versioning problem

### ISSUE THREAD

**Issue by hamdij0maa** [baronha/react-native-multiple-image-picker#122]
the last version working was : 1.1.2
the version that is install  by default now is : 1.1.5 
but its not working 
<img width="628" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/20734472/c0066b7c-521a-41e8-a215-98ef9ba63c59">

**Comment by baronha** [comment]
What happened to it? What is the error here? Please provide me with more details?

**Comment by baronha** [comment]
Do you call `openPicker()` function like this: 
```
import { openPicker } from '@baronha/react-native-multiple-image-picker';
// ...
const response = await openPicker(options);
```

**Comment by hamdij0maa** [comment]
Yes

**Comment by hamdij0maa** [comment]
It works in the version 1.1.2
The import and the call exactly like you mentioned 
But in version 1.1.5 you released nothing happens there is no error

**Comment by hamdij0maa** [comment]
try it on a fresh project, with installing it with : bun add ... / yarn add , it will install the 1.1.5 version ( that's not working ) 
the working version is 1.1.2 but it's not installed by default

**Comment by hamdij0maa** [comment]
@baronha I found the problem, 
when using : mediaType in options the openPicker is not working.

**Comment by baronha** [comment]
> @baronha I found the problem, when using : mediaType in options the openPicker is not working.

Show your code, please.

**Comment by hamdij0maa** [comment]
const pickerResSelected = await openPicker({
        numberOfColumn: 4,
        allowedLivePhotos: false,
        allowedPhotograph: selectedType === 'image' ? true : false,
        allowedVideo: selectedType === 'video' ? true : false,
        allowedVideoRecording: selectedType === 'video' ? true : false,
        singleSelectedMode: false,
        usedCameraButton: false,
        maxVideoDuration: 180,
        maximumMessageTitle: '',
        maximumMessage:
          selectedType === 'image'
            ? t('max-photos-reached')?.toString()
            : t('one-video-max')?.toString(),

        maxSelectedAssets: selectedType === 'image' ? 5 : 1,
        doneTitle: t('next'),
        usedPrefetch: true,

        isExportThumbnail: false,
        tapHereToChange: 'Album',
        cancelTitle: t('cancel'),
        autoPlay: true,
        isPreview: Platform.OS === 'ios' ? true : false,
        previewAtForceTouch: true,
        selectedColor: palette.lightBlue,
        emptyMessage: t('no-media-item-in-this-album')?.toString(),
        //@ts-ignore
        mediaType: selectedType === 'image' ? 'image' : 'video',
      });

**Comment by baronha** [comment]
Which OS are you on? `Android` or `iOS`
Here is an example on `iOS` with your code : 

https://github.com/baronha/react-native-multiple-image-picker/assets/23580920/bc1a849f-1fdc-46f2-a477-ab011e5e5856
