### ISSUE TITLE
IOS: Cannot select image when you limit photo library and mediaType = "all"

### ISSUE THREAD

**Issue by thanhtrung0301** [baronha/react-native-multiple-image-picker#123]
When mediaType is set to 'all' and limited photo library, the bottom sheet for selecting images will always appear, and I cannot select image/video.

**Comment by baronha** [comment]
Which version are you using (library version and iOS version)? And what is the bottom sheet you mentioned here?

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
