### ISSUE TITLE
Feat: Thêm option chụp ảnh

### ISSUE THREAD

**Issue by mduc-dev** [baronha/react-native-multiple-image-picker#126]
@baronha Chào bác, bác có thể thêm feat chụp ảnh vào options cho user sử dụng có thêm 1 option để chọn được không nhỉ 🤔🤔

**Comment by baronha** [comment]
Bác có thể mô tả rõ hơn không? Ý là muốn chụp ảnh thay vì mở Picker lên sau đó mới chụp đúng không ạ?

**Comment by ducnguyen4301** [comment]
> Bác có thể mô tả rõ hơn không? Ý là muốn chụp ảnh thay vì mở Picker lên sau đó mới chụp đúng không ạ?

![simulator_screenshot_27BC3B19-03D5-4A63-98A1-FD4CCBE5629A](https://github.com/baronha/react-native-multiple-image-picker/assets/80993895/b4faf652-29cd-4058-94f5-0e02ec8d1580)
như này nè bác, có thể chụp ảnh nữa thay vì chỉ chọn từ thư viện thui á bác.

**Comment by baronha** [comment]
À okay bác nhé. Phần này nằm ở trong TODO của mình. Nếu có thể thì bác cũng có thể tự viết tính năng này rồi PR cho mình
![Screenshot 2023-10-12 at 11 35 26](https://github.com/baronha/react-native-multiple-image-picker/assets/23580920/4c6d502d-a394-494a-af7c-ccb8aa4daf15)

**Comment by ducnguyen4301** [comment]
> À okay bác nhé. Phần này nằm ở trong TODO của mình. Nếu có thể thì bác cũng có thể tự viết tính năng này rồi PR cho mình ![Screenshot 2023-10-12 at 11 35 26](https://user-images.githubusercontent.com/23580920/274481966-4c6d502d-a394-494a-af7c-ccb8aa4daf15.png)

oke bác ơi, để rành rọt xíu tui thử viết lun 🤝

**Comment by baronha** [comment]
Mình đang làm phần này nhé: 
https://github.com/baronha/react-native-multiple-image-picker/pull/190

**Comment by baronha** [comment]
> Good work bác ơi, thanks bác đóng góp cho cộng đồng nhen.
Cám ơn bác đã ủng hộ nhiaaa

**Comment by baronha** [comment]
Kết quả đạt được:

https://github.com/user-attachments/assets/7afbc4cd-07a7-46b0-8501-9f1b3be70699
