### ISSUE TITLE
Migrate to New Architecture | HXPhotoPicker

### ISSUE THREAD

**Issue by baronha** [baronha/react-native-multiple-image-picker#127]

**Comment by baronha** [comment]
UPDATING....

**Comment by baronha** [comment]
In switching to new arch. I also converted TLPhotoPicker to [HXPhotoPicker](https://github.com/SilenceLove/HXPhotoPicker) at the same time

**Comment by ducpt-bili** [comment]
Hi @baronha , does your lib support new arch on 100%? Thanks

**Comment by amosaxe** [comment]
Damn, the HXPhotoPicker is having a lot of other features as well, so now do we have video editing support as well?

**Comment by baronha** [comment]
> Hi @baronha , does your lib support new arch on 100%? Thanks

The upcoming version is definitely there and is also backward compatible with the old arch

**Comment by baronha** [comment]
> Damn, the HXPhotoPicker is having a lot of other features as well, so now do we have video editing support as well?

Until I find a similar video editing solution on Android, I'll keep the two in sync

**Comment by baronha** [comment]
https://github.com/baronha/react-native-multiple-image-picker/pull/180

**Comment by baronha** [comment]
Done: https://baronha.github.io/react-native-multiple-image-picker/
