### ISSUE TITLE
Error 163 duplicate symbols for architecture x86_64  on IOS

### ISSUE THREAD

**Issue by minhpd911992** [baronha/react-native-multiple-image-picker#129]
When i upgrade version 1.1.6 and run project ios. It has an error:
163 duplicate symbols for architecture x86_64
Linker command failed with exit code 1 (use -v to see invocation)

If i use version 0.4.9, it hasn't error
My mac: Apple M1 Pro 16GB, Xcode 15, react native version 0.72.4

Please help me !

**Comment by marcos-vinicius-mafei** [comment]
Same problem here!

**Comment by marcos-vinicius-mafei** [comment]
@baronha, can you take a look at this? Pls!

**Comment by bizarrecoding** [comment]
I use this library in conjunction with another that uses TOCropViewController. This library uses CropViewController, which is a swift wrapper for the TOCropViewController, so it generates a second set of duplicated files.

**Comment by baronha** [comment]
> I use this library in conjunction with another that uses TOCropViewController. This library uses CropViewController, which is a swift wrapper for the TOCropViewController, so it generates a second set of duplicated files.

Yah sir. This is the right solution for us.
If you need to open the Crop View Controller directly, that's in my TODO list:

![Screenshot 2023-11-03 at 13 14 45](https://github.com/baronha/react-native-multiple-image-picker/assets/23580920/1db91535-0679-4d2e-9843-98ff9dd1411f)

**Comment by bizarrecoding** [comment]
Assuming you use another library using TOCropViewController, you need to patch it to use CropViewController instead.
In the other library podspec:
```
-  s.dependency 'TOCropViewController'
+  s.dependency 'CropViewController'
```
And within the library code replace any instance of TOCropViewController import:
```
-#import <TOCropViewController/TOCropViewController.h>
+#import <CropViewController/CropViewController.h>
```
with that, both libraries use the same dependency and will not generate duplicate files.

**Comment by marcos-vinicius-mafei** [comment]
Thank you so much @bizarrecoding!
I will try your solution.

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
