### ISSUE TITLE
rebuild fail on ios and android after install plugin

### ISSUE THREAD

**Issue by Seu07** [baronha/react-native-multiple-image-picker#13]
yarn add @baronha/react-native-multiple-image-picker 
(info.plist already configure)
cd ios/ && pod install
"$(TOOLCHAIN_DIR)/usr/lib/swift-5.3/$(PLATFORM_NAME)".  (and build on xcode got fail too)

+ error on android:
![Screen Shot 2021-05-06 at 1 41 53 PM](https://user-images.githubusercontent.com/29596908/117253016-ec5cb180-ae70-11eb-8b0e-ad970ff5ab92.png)

+ on ios
![Screen Shot 2021-05-06 at 12 28 03 PM](https://user-images.githubusercontent.com/29596908/117252446-2bd6ce00-ae70-11eb-8a9e-fc9ae51ea34b.png)
![Screen Shot 2021-05-06 at 12 28 42 PM](https://user-images.githubusercontent.com/29596908/117252465-31341880-ae70-11eb-9f84-d27f91afefab.png)
![Screen Shot 2021-05-06 at 12 28 58 PM](https://user-images.githubusercontent.com/29596908/117252471-32654580-ae70-11eb-81dc-6bf9645c3763.png)

**Comment by baronha** [comment]
in iOS. You have added file ```.swift``` in your project?

**Comment by zubyrbutt** [comment]
for android user if app crash after installing this package change to `classpath('com.android.tools.build:gradle:4.1.1')` in your **android/app/build.gradle** file
`buildscript { dependencies { classpath 'com.android.tools.build:gradle:4.0.1' } }`
after changing: 
**cd android** and run this commnand: `./gradlew clean`

**Comment by zubyrbutt** [comment]
**For android user**
app crashing after installing the package please check in these files:
1: Upgrade your gradle version by adding `classpath 'com.android.tools.build:gradle:4.0.1'` in your **android/build.gradle** file:
buildscript { dependencies { classpath 'com.android.tools.build:gradle:4.0.1' } }

2: goto **android/gradle/wrapper/gradle-wrapper.properties**
replace `distributionUrl=https\://services.gradle.org/distributions/gradle-X.X-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

3: add this line `multiDexEnabled true` in **android/app/build.gralde** file:
android {
    defaultConfig {
    applicationId "com.classmanager"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode 1
    versionName "1.0"
    **multiDexEnabled true**
    }

}
4:check `classpath("com.android.tools.build:gradle:4.1.1")` in file **android/build.gradle**
  dependencies {
        classpath("com.android.tools.build:gradle:4.1.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
I hope this will help you guys

**Comment by Seu07** [comment]
thank you)
