### ISSUE TITLE
Image is not showing in Gallery after capturing image in Camera

### ISSUE THREAD

**Issue by Naveen-ecrubit** [baronha/react-native-multiple-image-picker#130]
@baronha I am using oneplus mobile, for me the image is not showing in gallery after capturing image and clicking on the tick button. 

I have also checked in some mobiles, out of 5, only at one mobile this is working.

Can you look after this issue and provide a solution ?

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
