### ISSUE TITLE
duplicate symbol '_OBJC_CLASS_$_TOActivityCroppedImageProvider'

### ISSUE THREAD

**Issue by KartikLakhani009** [baronha/react-native-multiple-image-picker#133]
i install this lib and run xcode  got error like 

163 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i have check #108 issue and try everything but no luck

i have seen below symbol is use

duplicate symbol '_OBJC_CLASS_$_TOActivityCroppedImageProvider

i debug deeper and i find out like i have same packages and use in various packages
  - CropViewController (2.6.1)
  - react-native-multiple-image-picker (1.1.6):
    - CropViewController (= 2.6.1)
    - React-Core
    - react-native-multiple-image-picker/Viewer (= 1.1.6)
    - TLPhotoPicker (= 2.1.9)
  - react-native-multiple-image-picker/Viewer (1.1.6):
    - CropViewController (= 2.6.1)
    - React-Core
    - TLPhotoPicker (= 2.1.9)
    
    for CropViewController and
     - TOCropViewController (2.6.1)
      - RNImageCropPicker (0.36.4):
        - React-Core
        - React-RCTImage
        - RNImageCropPicker/QBImagePickerController (= 0.36.4)
        - TOCropViewController
     - RNImageCropPicker/QBImagePickerController (0.36.4):
        - React-Core
        - React-RCTImage
        - TOCropViewController
        
  if there is any help, please guide me      
  here is detail log file
        
[a.txt](https://github.com/baronha/react-native-multiple-image-picker/files/13546019/a.txt)

**Comment by Parkjunwu** [comment]
I got same problem!

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
