### ISSUE TITLE
0.73

### ISSUE THREAD

**Issue by TomWq** [baronha/react-native-multiple-image-picker#134]
After upgrading to rn0.73, Android will report an error indicating that some files cannot be found

R.drawable.ps_image_placeholder

**Comment by yinminqian** [comment]
解决了吗

**Comment by hamdij0maa** [comment]
+1

**Comment by TomWq** [comment]
Probably not much maintenance, the author has no reply in this regard

**Comment by TomWq** [comment]
But you can try to change R to com.luck.picture.lib.R is OK @hamdij0maa  @yinminqian

**Comment by hamdij0maa** [comment]
here a temp patch: 
package.json:
"scripts":{
"postinstall": "node ./patch.js"
}

file patch.js:

`const fs = require('node:fs');
const path = require('node:path');

const rootPath = path.join(__dirname, './');

const patchs = [
  [
    path.join(
      rootPath,
      '/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/GlideEngine.kt',
    ),
    `R.drawable.ps_image_placeholder`,
    `com.luck.picture.lib.R.drawable.ps_image_placeholder`,
  ],
];

(async () => {
  for (const [filePath, fromStr, toStr] of patchs) {
    console.log(`Patching ${filePath.replace(rootPath, '')}`);
    try {
      const file = (await fs.promises.readFile(filePath)).toString();
      await fs.promises.writeFile(filePath, file.replace(fromStr, toStr));
    } catch (err) {
      console.error(
        `Patch ${filePath.replace(rootPath, '')} failed: ${err?.message}`,
      );
    }
  }
  console.log('\nDependencies patch done.\n');
})();`

**Comment by chetanbhadarka** [comment]
> But you can try to change R to com.luck.picture.lib.R is OK @hamdij0maa @yinminqian

@TomWq Can you please explain more about solution if you found? does your issue pointed this errors?

#136

**Comment by Anhunghezo** [comment]
After chang R to "com.luck.picture.lib.R" in GlideEngine.kt and MultipleImagePickerModule.kt 

I still get errors:

e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:148:68 Unresolved reference: app_color_black
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:168:77 Unresolved reference: app_color_white
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:182:77 Unresolved reference: app_color_pri
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:184:77 Unresolved reference: app_color_pri
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:187:78 Unresolved reference: num_oval_orange
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:192:79 Unresolved reference: app_color_53575e
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:193:79 Unresolved reference: app_color_black
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:203:70 Unresolved reference: picture_selector
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:207:45 Unresolved reference: picture_selector
e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:223:46 Unresolved reference: app_color_white

**Comment by ngocdev97** [comment]
You can use the following method:
MultipleImagePickerModule.kt & GlideEngine.kt
import com.luck.picture.lib.R
import com.reactnativemultipleimagepicker.R.color
import com.reactnativemultipleimagepicker.R.drawable

**Comment by oluseyi-ged** [comment]
@ngocdev97 you are a life saver... Many thanks

**Comment by projektArkane** [comment]
> After chang R to "com.luck.picture.lib.R" in GlideEngine.kt and MultipleImagePickerModule.kt
> 
> I still get errors:
> 
> e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:148:68 Unresolved reference: app_color_black e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:168:77 Unresolved reference: app_color_white e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:182:77 Unresolved reference: app_color_pri e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:184:77 Unresolved reference: app_color_pri e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:187:78 Unresolved reference: num_oval_orange e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:192:79 Unresolved reference: app_color_53575e e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:193:79 Unresolved reference: app_color_black e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:203:70 Unresolved reference: picture_selector e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:207:45 Unresolved reference: picture_selector e: file:///Users/XXX/CODING/YYYYYYY/mobile/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:223:46 Unresolved reference: app_color_white

did you find any solution?

**Comment by baronha** [comment]
Solved v.1.1.9
Please check again for me

**Comment by Moryee** [comment]
@baronha the fix still doesn't work for me, it only works with the correct imports described here

> You can use the following method: MultipleImagePickerModule.kt & GlideEngine.kt import com.luck.picture.lib.R import com.reactnativemultipleimagepicker.R.color import com.reactnativemultipleimagepicker.R.drawable [@baronha+react-native-multiple-image-picker+1.1.6.patch](https://github.com/user-attachments/files/15849397/%40baronha%2Breact-native-multiple-image-picker%2B1.1.6.patch)

**Comment by SnakeLil** [comment]
@baronha  same problem , 
"@baronha/react-native-multiple-image-picker": "^1.1.9",
The fix still doesn't work for me 🙏🙏🙏

**Comment by baronha** [comment]
> @baronha same problem , "@baronha/react-native-multiple-image-picker": "^1.1.9", The fix still doesn't work for me 🙏🙏🙏

oh no. So please use version 1.1.8. I made a mistake when editing the code.

**Comment by SnakeLil** [comment]
I used the patch, @ngocdev97  suggested and used version 1.1.6, but it would be even better if you could fix it！Thank you～

**Comment by SnakeLil** [comment]
> > @baronha same problem , "@baronha/react-native-multiple-image-picker": "^1.1.9", The fix still doesn't work for me 🙏🙏🙏
> 
> oh no. So please use version 1.1.8. I made a mistake when editing the code.

I used the patch, @ngocdev97 suggested and used version 1.1.6, but it would be even better if you could fix it！Thank you～

**Comment by ngocdev97** [comment]
Patch file for 1.1.9:
[@baronha+react-native-multiple-image-picker+1.1.9.patch](https://github.com/user-attachments/files/16597482/%40baronha%2Breact-native-multiple-image-picker%2B1.1.9.patch)

**Comment by Menzen20** [comment]
> @baronha+react-native-multiple-image-picker+1.1.9.patch

Thanks a lot @ngocleexuan works for me
