### ISSUE TITLE
Problem building in xcode

### ISSUE THREAD

**Issue by TallNutAlt** [baronha/react-native-multiple-image-picker#135]
/Users/jiao/Library/Developer/Xcode/DerivedData/MyProject-aesffzqtplothievmqpvdkdzimhq/Build/Intermediates.noindex/MyProject.build/Debug-iphoneos/MyProject.build/DerivedSources/MyProject_vers.c module map file '/Users/jiao/Library/Developer/Xcode/DerivedData/MyProject-aesffzqtplothievmqpvdkdzimhq/Build/Products/Debug-iphoneos/CropViewController/CropViewController.modulemap' not found

**Comment by Ahsanali012** [comment]
Getting the same error

**Comment by vivkikkk** [comment]
same

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
