### ISSUE TITLE
Caused by: org.jetbrains.kotlin.gradle.tasks.CompilationErrorException: Compilation error. See log for more details

### ISSUE THREAD

**Issue by yinminqian** [baronha/react-native-multiple-image-picker#136]
<img width="1719" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/28828271/f10a8d6d-b1fd-4435-a8e1-70d35202cb15">

i just init new react native project,version is 0.73 ,when i use run  , i got a error。look this image ,just android have error，ios is ok 。

this is my react native info 
System:
  OS: macOS 14.1.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 104.27 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/yinminqian/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/yinminqian/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by yinminqian** [comment]
<img width="1246" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/28828271/370c51da-96ca-4493-920a-9d1a87be0be1">
<img width="1532" alt="image" src="https://github.com/baronha/react-native-multiple-image-picker/assets/28828271/9991cf7f-be4b-4372-99bd-b95168a86d87">
 
Based on my intuition, I feel that it has something to do with this, but I modified it to 1.8.0, which does not solve the problem. Please help me.

**Comment by quoctruongkt** [comment]
I'm also having the same problem, do you have any solution?

**Comment by ddvalereio** [comment]
Stuck with same issue.. please suggest any solution.
Library is not supported for 0.73

**Comment by baronha** [comment]
OMG. I think I need to upgrade the library.

**Comment by chetanbhadarka** [comment]
**Same issue.**
```
Caused by: org.jetbrains.kotlin.gradle.tasks.CompilationErrorException: Compilation error. See log for more details
```

```
> Task :baronha_react-native-multiple-image-picker:compileDebugKotlin FAILED
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/GlideEngine.kt:67:31 Unresolved reference: ps_image_placeholder
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/GlideEngine.kt:86:31 Unresolved reference: ps_image_placeholder
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:162:52 Unresolved reference: anim
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:163:51 Unresolved reference: anim
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:173:61 Unresolved reference: ps_album_bg
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:174:59 Unresolved reference: ps_ic_grey_arrow
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:175:61 Unresolved reference: ps_ic_black_back
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:176:54 Unresolved reference: ps_ic_black_back
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:186:56 Unresolved reference: ps_color_white
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:189:56 Unresolved reference: ps_color_53575e
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:191:56 Unresolved reference: ps_color_53575e
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:205:56 Unresolved reference: ps_color_white
e: /node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:216:56 Unresolved reference: ps_color_9b
```

```
"@baronha/react-native-multiple-image-picker": "^1.1.6",
"react-native": "0.73.2",
```

**Comment by eldynguyen1204** [comment]
+1

**Comment by RogerIn1900** [comment]
same issue
![image](https://github.com/baronha/react-native-multiple-image-picker/assets/150680014/f6620215-b43e-4488-9a54-c5217ff1666f)

**Comment by RogerIn1900** [comment]
And I found some infos here
![image](https://github.com/baronha/react-native-multiple-image-picker/assets/150680014/5fdfbd79-520b-4876-9b0d-dab8bd1007d6)

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/

**Comment by Samama-Zargham** [comment]
To change these versions helped for me🤍🤍🤍❤️❤️❤️❤️ 

"react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.27.0",
