### ISSUE TITLE
[IOS] Loading forever when select image limit access

### ISSUE THREAD

**Issue by truongtv-3223** [baronha/react-native-multiple-image-picker#141]
I encountered 2 problems when selecting photos in the case of granting permission to select photos on iOS as limit access.
- problem 1: with library versions 1.1.2. When I grant limit access permission and then select the list of images allowed to access, this screen will be opened indefinitely without being allowed to switch to another screen (same issue same issue https://github.com/baronha/react-native-multiple-image-picker/issues/123)
- problem 2: Because of problem 1, I decided to use a lower version of the library <= 1.1.0 and I don't have problem 1 anymore. But I encountered another problem: in screen A selecting image from the list of images that have been granted limited access rights, I selected image X, then I clicked on the image button (next to the done button) to go to screen B select the limit access image list again and remove access to image X, then return to screen A and click done which will result in loading forever

@baronha

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
