### ISSUE TITLE
App Crash on Android real device when click done.

### ISSUE THREAD

**Issue by chetanbhadarka** [baronha/react-native-multiple-image-picker#142]
```
const response = await openPicker({
  mediaType: 'video',
  maxSelectedAssets: 1,
  allowedLivePhotos: false,
  selectedAssets: allVideos,
});
```

**Issue:**
- When i select a video and then press "done", my app is crashed.
- It only happens for first time. If i came back then it's working as expected.
- I also do console "response" and I got the array of records even if app crashed.

**Comment by baronha** [comment]
Which operating system are you using? What is the version?

**Comment by chetanbhadarka** [comment]
> Which operating system are you using? What is the react-native's version and the os version?

RN: **v0.73.2**
Android: **v11**
react-native-multiple-image-picker: **v1.1.2**

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
