### ISSUE TITLE
Task :baronha_react-native-multiple-image-picker:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by sarthaksnh5** [baronha/react-native-multiple-image-picker#144]
Getting this error after installing library.

Version is as follows:
"react": "18.2.0",
"@baronha/react-native-multiple-image-picker": "1.1.6",

**Comment by itjuh** [comment]
https://github.com/baronha/react-native-multiple-image-picker/issues/134
Refer to this article and change ### R. in the compilation error code to ### com.luck.picture.lib.R. I solved the error this way.

**Comment by sarthaksnh5** [comment]
But where do I need to replace this R?

**Comment by Anhunghezo** [comment]
> where do I need to replace this R?

Can you show me where to replace this "R"?

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
