### ISSUE TITLE
`selectedColor` prop is not working on Android

### ISSUE THREAD

**Issue by changwoolab** [baronha/react-native-multiple-image-picker#145]
`selectedColor` prop works well on iOS but is not working on Android
it changes the "selectTextColor" but not the markers of select images. 

It would be great if it is possible to customize colors in `colors.xml`!

**Comment by StephenLeeSC** [comment]
```
// colors.xml

...
<color name="app_color_pri">#2570fc</color>
...
```

you can set like this. it's working for me.

**Comment by changwoolab** [comment]
What I wanted is to customize through props! not by patch-package colors.xml
