### ISSUE TITLE
GIFs not displaying for Android devices

### ISSUE THREAD

**Issue by panwarRohit123** [baronha/react-native-multiple-image-picker#146]
Whenever I open the gallery of Android devices, this plugin ignores all GIF files, so I don't see any option for select GIF.

**Comment by panwarRohit123** [comment]
@baronha Please give any solution. How can i resolve it this problem ?

**Comment by baronha** [comment]
> @baronha Please give any solution. How can i resolve it this problem ?
I will check the native library on the Android side to see if this can be resolved.

**Comment by lqscrisp7** [comment]
> > @baronha Please give any solution. How can i resolve it this problem ?
> 
> I will check the native library on the Android side to see if this can be resolved.

Hi, can help to solve this issue?

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
