### ISSUE TITLE
[Question] Record video on iOS?

### ISSUE THREAD

**Issue by anhquan291** [baronha/react-native-multiple-image-picker#15]
Hi,

It's me again :D. I have a question that is there an option to record video from the camera button? It only can take photos now on iOS. 

Thank you so much

**Comment by baronha** [comment]
It was crashing on iOS so I turned it off. I will re-open this feature soon in the future

**Comment by anhquan291** [comment]
> It was crashing on iOS so I turned it off. I will re-open this feature soon in the future

Thank you so much. Have a great day

**Comment by aminmahrami** [comment]
@baronha can you provide some information about the crash in case someone wanted to debug it?

**Comment by devilabhi** [comment]
Any updates with this?
