### ISSUE TITLE
[Android] Google Play's Photo and Video Permissions policy.

### ISSUE THREAD

**Issue by sean5940** [baronha/react-native-multiple-image-picker#151]
https://support.google.com/googleplay/android-developer/answer/14115180

Timeline information
See the following timeline for the Photo and Video Permissions policy. Note that this is subject to change; updates will be posted in this article.

October 2023: We announced the new Photos and Video Permissions policy.
August 31, 2024:

Apps with one-time or infrequent use of photos are requested to remove READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions from their app manifest and migrate to a system photo picker if necessary.

Apps with one-time or infrequent use that need time to remove permissions or migrate to a picker can request an extension until January 2025.

Apps with core use-case or broad access use can begin providing use-case rationale using the declaration form within Play Console.

In the given situation, it is necessary to remove the permissions. However, removing these permissions causes the library to not function correctly, so assistance is needed.

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/

**Comment by esse1441** [comment]
https://github.com/NitrogenZLab/react-native-multiple-image-picker/blob/6c531f3f60d7a2ed238386c38f2ee85f55d970f9/android/src/main/AndroidManifest.xml#L14-L16

It seems that it is still using those permissions. READ_MEDIA_IMAGES and READ_MEDIA_VIDEOS

**Comment by woodsandwalker** [comment]
@esse1441 did you resolve this?
