### ISSUE TITLE
không hiển thị video dài hoặc đã tải xuống

### ISSUE THREAD

**Issue by cuongtq100** [baronha/react-native-multiple-image-picker#152]
mình chọn video thì nó không show những video mình tải xuống(ví dụ tải video từ tiktok hay quay màn hình), mình muốn chọn những video dài mà không thấy xuất hiện, chỉ có những video ngắn

**Comment by cuongtq100** [comment]
sorry, chỉ là không xuất hiện video trên 1 phút thôi ạ

**Comment by NguyenHoangMinhkkkk** [comment]
> Có một options liên quan đến duration của Video: https://github.com/baronha/react-native-multiple-image-picker?tab=readme-ov-file#options Mình đang để mặc định là 60s nhé. ![Screenshot 2024-06-05 at 15 20 57](https://private-user-images.githubusercontent.com/23580920/336752334-24e5946e-aed1-4e11-a1e8-86809bb486bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzgxMTQsIm5iZiI6MTcxNzU3NzgxNCwicGF0aCI6Ii8yMzU4MDkyMC8zMzY3NTIzMzQtMjRlNTk0NmUtYWVkMS00ZTExLWExZTgtODY4MDliYjQ4NmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmRmYjU4NWUxYjVlYjQyZmUyYmQ5OTMxN2I1M2JkNzEwNmVkOGMwODdjZjAxNGNmYWUzMGZlZmNhMzJkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFYuplOVGH3hOaQQAY0-0MFm_lbOUfYnh862bRrHGLA)

mình muốn chọn các video có độ dài <= 60 giây, nhưng vẫng chọn được các video dài hơn dù đã set maxvideoduration = 60.
sau khi đã có videoresult cũng ko biết duration của video đã chọn có >60 giây hay không, để reject video đã chọn. bạn có idea nào không ?

**Comment by NguyenHoangMinhkkkk** [comment]
MultipleImagePicker.openPicker({
      mediaType: 'video' as MediaType,
      singleSelectedMode: true,
      isPreview: true,
      usedCameraButton: true,
      allowedVideoRecording: true,
      doneTitle: t('button:done'),
      cancelTitle: t('button:cancel'),
      maxVideoDuration: 59,
    });
    
Mình cũng thắc mắc. iOS thì đúng là ko hiện các video >60s, nhưng ở Android thì có. 
test trên device thật - pixel 3a android 12.
> @NguyenHoangMinhkkkk maxvideoduration=60 thì nó có hiện những video lớn hơn 60s đâu mà chọn được bạn.

**Comment by cuongtq100** [comment]
@NguyenHoangMinhkkkk vậy thì ở response bạn check thêm, có trả về duration đó, đơn vị khác nhau thôi, ios thì sẵn là giây rồi bạn check nếu response[0]?.duration > secondCheck thì thông báo không được quá, còn android thì response[0]?.duration/60000 > secondCheck thì thông báo không được quá. mình thấy duration trả về ở 2 bên khác nhau về đơn vị đó

**Comment by NguyenHoangMinhkkkk** [comment]
> @NguyenHoangMinhkkkk vậy thì ở response bạn check thêm, có trả về duration đó, đơn vị khác nhau thôi, ios thì sẵn là giây rồi bạn check nếu response[0]?.duration > secondCheck thì thông báo không được quá, còn android thì response[0]?.duration/60000 > secondCheck thì thông báo không được quá. mình thấy duration trả về ở 2 bên khác nhau về đơn vị đó

mình chọn 1 video 9:41s. thì response cho duration là 581000, thì /1000 = số giây của video = 581s

**Comment by cuongtq100** [comment]
@NguyenHoangMinhkkkk  đang ko biết trên android có trả về cùng 1 đơn vị không nữa

**Comment by NguyenHoangMinhkkkk** [comment]
> @NguyenHoangMinhkkkk đang ko biết trên android có trả về cùng 1 đơn vị không nữa.chỉ sợ các thiết bị khác nhau lại có đơn vị khác nhau

mình cũng không thấy define duration trong typescript, nên mới ko rõ nó có tồn tại hay không
