### ISSUE TITLE
Showing Chinese as default language when the device default language is unsupported

### ISSUE THREAD

**Issue by bevisgan** [baronha/react-native-multiple-image-picker#154]
Hi, 

I found an issue is that, when the phone's language selected Indonesia, it showing Chinese instead of English, please check out the image attached below.  

Could anyone please help on this issue? Thanks in advance! 

![WhatsApp Image 2024-06-10 at 6 28 03 PM](https://github.com/baronha/react-native-multiple-image-picker/assets/23733618/798d6a7a-2c8a-46f1-ae29-015cbeeadbf2)

Thanks and Regards,
Bevis.

**Comment by MykolaRomaniv** [comment]
Same problem here.
The only solution I found was to "force" English language in the android native code
https://stackoverflow.com/a/9173571

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/

**Comment by PierreCapo** [comment]
@baronha I still have the issue on my side even if I force the language with the `language` option.
