### ISSUE TITLE
trigger openPicker không xảy ra phản ứng gì cả

### ISSUE THREAD

**Issue by lamlengend98** [baronha/react-native-multiple-image-picker#155]
HI @baronha , mình đang sử dụng version mới nhất, sau khi trigger function openPicker thì ko xảy ra hiện tượng gì cả, cũng ko có log ở catch luôn

```
  const onAddImage = async () => {
    console.log('🚀 ~ onAddImage ~ onAddImage:')

    openPicker({
      mediaType: MediaType.IMAGE,
      selectedAssets: files,
      isExportThumbnail: true,
      doneTitle: 'Xong',
      usedCameraButton: false,
    }).catch((error) => {
      console.log('🚀 ~ onAddImage ~ error:', error)
    })
    // console.log('🚀 ~ onAddImage ~ assets:', assets)

    // if (assets?.length) setFiles(assets)
  }
```

```
    "react-native": "0.74.1",
    "@baronha/react-native-multiple-image-picker": "^1.1.2",
```
Không biết có phải do version React Native ko
có thời gian bạn check qua giúp mình với nhé

**Comment by hieuphan1030** [comment]
@lamlengend98 Bạn thêm `await` trước `openPicker` là được nha

<img width="872" alt="Screenshot 2024-07-25 at 4 39 07 PM" src="https://github.com/user-attachments/assets/26c8ee31-985b-4fe3-b81c-9d0c6c7a1b47">
