### ISSUE TITLE
How to hide album selector ?

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [baronha/react-native-multiple-image-picker#157]
Hi, On Android, is it available for hiding album selector and show anything from Gallery instead ? 

![Screenshot 2024-07-09 at 15 32 59](https://github.com/baronha/react-native-multiple-image-picker/assets/30792140/ad3e0381-d135-4ada-b2b9-ef51025978e8)

**Comment by baronha** [comment]
Currently, that feature is not supported. You will have to wait for a few upcoming updates.
Sorry.
