### ISSUE TITLE
Android : Image Don't Display after crop 

### ISSUE THREAD

**Issue by Puthsihta** [baronha/react-native-multiple-image-picker#161]
**This is the Respone of the Image**

[
  "medias : ",
  {
    "size": 5799270,
    "duration": 0,
    "chooseModel": 1,
    "localIdentifier": 1000006209,
    "mime": "image/png",
    "path": "content://media/external/images/media/1000006209",
    "height": 800,
    "crop": {
      "height": 800,
      "width": 800,
      "path": "/storage/emulated/0/Android/data/com.bongtk.bloc/files/Pictures/CROP_20240719103550494.jpg"
    },
    "parentFolderName": "Screens",
    "width": 1920,
    "fileName": "The.Boys.S04E06.1080p.x265-ELiTE.Screen0003.png",
    "realPath": "/storage/emulated/0/Download/The.Boys.S04E06.1080p.x265-ELiTE/Screens/The.Boys.S04E06.1080p.x265-ELiTE.Screen0003.png",
    "bucketId": -986766711,
    "position": 3,
    "type": "image"
  }
]

**I display image by using Image React Native**

<Image source={{uri : respone.crop.path}} style={{width: 200, height: 200}}/>

**Comment by Puthsihta** [comment]
But when I use respone.path 
it displays but not crop.

**Comment by baronha** [comment]
Solved v.1.1.9
Please check again for me
