### ISSUE TITLE
Lỗi hiển thị Android

### ISSUE THREAD

**Issue by hungdomanh95** [baronha/react-native-multiple-image-picker#163]
Chào anh,

Em đang dùng 
 "react-native": "0.71.3",
 "@baronha/react-native-multiple-image-picker": "^1.1.7"

Bị lỗi hiển thị như video sau, khi chọn ảnh  xong hoặc back về thì bị lỗi hiển thị chớp 1 cái rồi mới tắt, chỉ bị trên android, ios không bị. Có cách nào fix nhanh lỗi này không ạ.

https://github.com/user-attachments/assets/61253432-9dff-4efc-af7a-e38e8d646594

**Comment by baronha** [comment]
Oke em. Cái này để anh tái hiện lại thử rồi fix nhé, Sẽ mất một khoảng thời gian.

**Comment by cd-butterfly** [comment]
@baronha https://github.com/baronha/react-native-multiple-image-picker/pull/162 my pull request fixed this issue,please review it
