### ISSUE TITLE
How to have fixed height and width of the cropped image

### ISSUE THREAD

**Issue by amosaxe** [baronha/react-native-multiple-image-picker#168]
Hi, Great work and features in this library, is there a way to force a fixed height and width(i.e., a fixed aspect ratio) while cropping the asset?

**Comment by amosaxe** [comment]
Sorry to bug you @baronha, but if you or anyone can help me with the above info, I can close my work, everything is great in this lib when compared to image-crop-picker in terms of performance, just this particular option can become a blocker.

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
