### ISSUE TITLE
Add previewButton text and toggle property

### ISSUE THREAD

**Issue by victorCodeLabs** [baronha/react-native-multiple-image-picker#169]
Currently on Spanish devices, the preview button option at the bottom bar of the picker says "preestrenar (5)" and that is not the correct translation it should be "previsualizar". Is possible to get a property to override this text like the done title and cancel title?

Also, it would be great to have the possibility to disable the preview button if its possible

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
