### ISSUE TITLE
Accessibility support (Voice Over)

### ISSUE THREAD

**Issue by xMonty** [baronha/react-native-multiple-image-picker#171]
Hi,
When voice over is enabled its not possible to move focus to thumbnails of images on iOS, on Android it works great, add two lines
to cell.swift makes it work

File: cell.swift

override func awakeFromNib() {
        super.awakeFromNib()

        //Adding these lines to make the cell accessible
        self.isAccessibilityElement = true
        self.accessibilityLabel = "Photo thumbnail"
        
        self.playerView?.playerLayer.videoGravity = AVLayerVideoGravity.resizeAspectFill
        self.durationView?.backgroundColor = UIColor.clear
        self.orderLabel?.clipsToBounds = true
        self.orderLabel?.layer.cornerRadius = 12
        self.orderLabel?.layer.borderWidth = 2
        self.orderLabel?.layer.borderColor = UIColor.white.cgColor
        self.videoIconImageView?.image = config.videoIcon
        if #available(iOS 11.0, *) {
            self.imageView?.accessibilityIgnoresInvertColors = true
            self.playerView?.accessibilityIgnoresInvertColors = true
            self.livePhotoView?.accessibilityIgnoresInvertColors = true
            self.videoIconImageView?.accessibilityIgnoresInvertColors = true
        }
    }

**Comment by baronha** [comment]
Please PR for me.
