### ISSUE TITLE
Too Much delay and app got stuck

### ISSUE THREAD

**Issue by jazzylamba** [baronha/react-native-multiple-image-picker#172]
After selection media on done click there is too much loading time app got struck and i am unable to perform on do any thing except minimise and remove app and then restart app  on simulator (iphone 15 promax)
 i am using like 
 
 ```
   const options = {
        usedCameraButton: false,
        isExportThumbnail: true,
        // maxVideo:10,
        // maxSelectedAssets: 20,
        allowedLivePhotos: true,
        emptyMessage: 'No media found',
        maximumMessageTitle: 'Maximum Selection limit reached',
        numberOfColumn:3
      };
const result = await openPicker(options);
```

**Comment by ghulamrasool1** [comment]
True, further, I noticed it happens when a user uses it for the first time, every subsequent time, it appears to be faster, anyone has any clue?

**Comment by baronha** [comment]
@jazzylamba @ghulamrasool1 
Sorry for the bad experience above. I'm refactoring and will release version 2.0 in the next few weeks

**Comment by ghulamrasool1** [comment]
any workaround you can suggest meanwhile?

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
