### ISSUE TITLE
baronha_react-native-multiple-image-picker:compileDebugKotlin

### ISSUE THREAD

**Issue by cuongtq100** [baronha/react-native-multiple-image-picker#174]
hôm nay mình chạy dự án android thì báo lỗi này, ai biết fix không ạ
* What went wrong:
Execution failed for task ':baronha_react-native-multiple-image-picker:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by cuongtq100** [comment]
nó báo như này ạ
node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:176:54 Unresolved reference: ps_ic_black_back
/node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:186:56 Unresolved reference: ps_color_white
node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:189:56 Unresolved reference: ps_color_53575e

**Comment by baronha** [comment]
Bạn thử downgrade về version trước đó xem.

**Comment by baronha** [comment]
Sắp tới mình có đợt chỉnh sửa lớn cho thư viện nên là mấy lỗi này cũng được fix trong phiên bản tới luôn nghen

**Comment by krisnapy** [comment]
Any updates? I'm having the same problem.

**Comment by rockcheung2004** [comment]
I got this error on 1.1.9, downgraded to 1.1.8 and it builds successfully again.

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
