### ISSUE TITLE
iOS crash when select multiple and cancel

### ISSUE THREAD

**Issue by StephenLeeSC** [baronha/react-native-multiple-image-picker#175]
in iOS, when i select multiple photo and cancel after select
cancellation is not working.
and it crash sometimes

here's some video i record
https://github.com/user-attachments/assets/4f6731f5-a794-4af7-8b80-312e732d3c61

i think it happens in newer iphone?

iPhone 14 pro with iOS 18.1 happend
iPhone 13 pro with iOS 17.5.1 not happend
iPhone se 2 with iOS 18.1 not happened

**Comment by letrunghieu0803** [comment]
i have same issue. Any answer for this ticket ?

**Comment by letrunghieu0803** [comment]
On my case, i founded solution for this:

in MultipleImagePicker.swift , 
replace :
`let cell = picker.collectionView(picker.collectionView, cellForItemAt: IndexPath.init(row: at, section: 0)) as! Cell`
to
`let cell = picker.collectionView.cellForItem(at: IndexPath(row: at, section: 0)) as? Cell`

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
