### ISSUE TITLE
Có cách nào chỉ sử dụng tính năng react-native-image-picker không

### ISSUE THREAD

**Issue by yet-phuc** [baronha/react-native-multiple-image-picker#177]
Làm sao tôi chỉ muốn sử dụng tính năng launchImageLibrary của react-native-image-picker, có thể truyền mảng ảnh đã chọn trước đó vào không? như option selectedAssets vậy, hoặc có đoạn code nào để folk thư viện react-native-image-picker để có thể thêm options selectedAssets như tôi mong muốn không

**Comment by baronha** [comment]
Có lẽ bro đã vào nhầm thư viện rồi 🥺

**Comment by yet-phuc** [comment]
Có thư viện nào khác mà có thể truyền ảnh đã chọn vào lại thư viện chọn ảnh không bro

**Comment by baronha** [comment]
> Có thư viện nào khác mà có thể truyền ảnh đã chọn vào lại thư viện chọn ảnh không bro

Hmmm. Không biết bro ơi. Chỉ vì không kiếm được thư viện nào khác nên là thư viện này mới ra đời.
