### ISSUE TITLE
'Done' button does not return anything when selectedAssets is initialized without changes

### ISSUE THREAD

**Issue by krisnapy** [baronha/react-native-multiple-image-picker#178]
Steps to Reproduce:
1. Initialize the selectedAssets prop with a list of assets.
2. Call the `openPicker` function without making any changes to the selected assets.
3. Press the 'Done' button.

Expected Behavior:
The 'Done' button should resolve the promise and return the selected assets, even if no changes were made.

Actual Behavior:
The 'Done' button does not return anything, causing the promise to remain unresolved.

**Comment by baronha** [comment]
Please check new version: 2.0
