### ISSUE TITLE
Error when building on android - Unresolved reference: anim

### ISSUE THREAD

**Issue by viocuong** [baronha/react-native-multiple-image-picker#179]
Enviroment
React native:  0.74.1
react-native-multiple-image-picker: 1.1.9
Error: 
- node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:169:60 Unresolved reference: ps_album_bg
- node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/MultipleImagePickerModule.kt:159:51 Unresolved reference: anim
- ....

**Comment by baronha** [comment]
Downgrade 1.1.8 please.
Forgive me. In the upcoming version I will fix all these mistakes

**Comment by viocuong** [comment]
@baronha 
`singleSelectedMode?: false`; 
Hình như type sai anh ạ

**Comment by baronha** [comment]
> @baronha `singleSelectedMode?: false`; Hình như type sai anh ạ

Kệ ló đi bạn. Sắp tới mình sẽ release phiên bản 2.0

**Comment by viocuong** [comment]
Anh có task gì cần không em contrib với

**Comment by baronha** [comment]
Mình chưa có nhé. Nếu phát hiện lỗi nào bạn cứ PR thoải mái cho mình nha
