### ISSUE TITLE
When used on actual devices, sometimes numbers duplicate in the media grid view, and there is a delay when deselecting.

### ISSUE THREAD

**Issue by RyeolRyeol** [baronha/react-native-multiple-image-picker#181]
Hello, I am using an iPhone 11. The app works as expected on the simulator, but on an actual device, sometimes when I select and deselect multiple media items, the numbers are duplicated on the screen. In these cases, after some time or after a refresh, everything returns to normal. Also, there is sometimes a delay when deselecting. Could it be that I have set some options incorrectly?

**Comment by baronha** [comment]
Please check new version 2.0
