### ISSUE TITLE
Typescript types file location is incorrect

### ISSUE THREAD

**Issue by imranbarbhuiya** [baronha/react-native-multiple-image-picker#192]
file structure inside lib is like this
![image](https://github.com/user-attachments/assets/416f3f6f-da73-48b9-a031-d1528b26a7c4)
but types say `lib/index.d.ts` exists
![image](https://github.com/user-attachments/assets/ae6fb9bb-5131-4258-b73e-4547ff53fe61)

I can create a pr to fix it but first I wanted to know if it's an issue happening to only me or others are also having the same issue

**Comment by baronha** [comment]
Solved by @jeongshin 
https://github.com/baronha/react-native-multiple-image-picker/pull/193#event-15659932333
