### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by antoinefotso** [baronha/react-native-multiple-image-picker#2]
this package is working very well.
but i have following error when i use it with react-native-photo-editor.

Duplicate class com.yalantis.ucrop.view.OverlayView$FreestyleMode found in modules jetified-ucrop-2.2.2-native-runtime.jar (com.github.yalantis:ucrop:2.2.2-native) and jetified-ucrop-v2.6.0-runtime.jar (com.github.LuckSiege.PictureSelector:ucrop:v2.6.0)

Do you know how  can i solve this ?

**Comment by baronha** [comment]
Have you solved it yet? If not, please update the new version. Thank you.
