### ISSUE TITLE
Can't build on xcode

### ISSUE THREAD

**Issue by nicgutierrez** [baronha/react-native-multiple-image-picker#20]
Hi! 

I followed the instructions on the readme for xcode 12.4, however, I can't get the build working.

I'm getting tons of errors, here's a screenshot:

![image](https://user-images.githubusercontent.com/436432/120112754-684bd000-c177-11eb-9f05-bc73f97b20c6.png)

Any ideas on how to fix it? 

Cheers!

**Comment by baronha** [comment]
you can try to add file .swift in your project. Because this lib was written based on swift instead of obj c. If the build is successful please let me know. Thanks.

**Comment by nicgutierrez** [comment]
> You can try to add file .swift in your project. Because this lib was written based on swift instead of obj c. If the build is successful please let me know. Thanks.

Hey @baronha

What do you mean by adding "a swift file"? Which one should I be adding? Thanks

**Comment by baronha** [comment]
Check out this link: https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios
