### ISSUE TITLE
'HybridContext' is deprecated: Update Nitrogen and re-generate your specs

### ISSUE THREAD

**Issue by ertucaglar** [baronha/react-native-multiple-image-picker#200]
I upgrade react-native-nitro-modules from 0.18.2 to 0.19.0 then I got iOS build error

<img width="1329" alt="image" src="https://github.com/user-attachments/assets/90d3c8ef-bb97-46a2-aa66-326ede5140d8" />

low priority for me, I'm using with 0.18.2

**Comment by baronha** [comment]
Today, bro

![image](https://github.com/user-attachments/assets/d483334e-7fd1-445e-b6fe-73903f0f5606)

**Comment by baronha** [comment]
I think u keep Nitro on 0.18.2
I had some bugs when upgrading to Nitro 19

**Comment by baronha** [comment]
Check new version 2.1.2
