### ISSUE TITLE
cppPart.pointee: Cannot use mutating member on immutable value: 'pointee' is a get-only property

### ISSUE THREAD

**Issue by khanwilson** [baronha/react-native-multiple-image-picker#201]
i'm using 
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-nitro-modules": "^0.19.0",
    "@baronha/react-native-multiple-image-picker": "^2.1.0",
    
    after setting up, when i build on xcode got this
    
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/a1a42f37-1520-403a-a4c1-476dfa2cbeb8" />

**Comment by baronha** [comment]
You should use Nitro 0.18.2.
The latest version of Nitro Module is corrupted.
