### ISSUE TITLE
Selecting and De-selecting media is broken: count is wrong and I can’t deselect the selected media

### ISSUE THREAD

**Issue by jazzylamba** [baronha/react-native-multiple-image-picker#211]
Selecting and De-selecting media is broken: count is wrong and I can’t deselect the selected media

[https://staging-brand.oono.ai/test-one?collection=select--unselect&brandId=test-one&story=0](https://staging-brand.oono.ai/test-one?collection=select--unselect&brandId=test-one&story=0)

  "@baronha/react-native-multiple-image-picker": "^1.1.9",

**Comment by baronha** [comment]
Please provide the current version you are using. If < 2.0 then sorry I no longer support that version

**Comment by jazzylamba** [comment]
> Please provide the current version you are using. If < 2.0 then sorry I no longer support that version

when a add using `yarn add  @birdwingo/react-native-instagram-stories`
the "@birdwingo/react-native-instagram-stories": "1.3.8", version added

**Comment by jazzylamba** [comment]
> Please provide the current version you are using. If < 2.0 then sorry I no longer support that version
when i am adding  using `yarn add @baronha/react-native-multiple-image-picker` its adding
"@baronha/react-native-multiple-image-picker": "^1.1.9",

**Comment by baronha** [comment]
As mentioned above. Versions < 2.0 are no longer supported. If you need a quick fix, follow the instructions in this issue:
https://github.com/baronha/react-native-multiple-image-picker/issues/175#issuecomment-2482172891

**Comment by jazzylamba** [comment]
after updatein

> As mentioned above. Versions < 2.0 are no longer supported. If you need a quick fix, follow the instructions in this issue: [#175 (comment)](https://github.com/baronha/react-native-multiple-image-picker/issues/175#issuecomment-2482172891)

after updation its showing error on pod install
```
[!] Unable to find a specification for `NitroModules` depended upon by `MultipleImagePicker`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by jazzylamba** [comment]
`Build service could not create build operation: unknown error while handling message: MsgHandlingError(message: "unable to initiate PIF transfer session (operation in progress?)")`
after updating showing a new error

**Comment by baronha** [comment]
How version React Native are you using?
This is requirement:
https://baronha.github.io/react-native-multiple-image-picker/getting-started#requirements
