### ISSUE TITLE
Getting different keys from response object

### ISSUE THREAD

**Issue by Janviba911** [baronha/react-native-multiple-image-picker#22]
In android, we are getting **fileName**, **mine** but in iOS we are getting **filename**, **mime** from response.
Please make it both same.

**Comment by BhaveshShadija1313** [comment]
i am also facing same issue.Please make it both same ASAP.

**Comment by baronha** [comment]
Yup. I will finish it soon

**Comment by vivianlys90** [comment]
Please also change for key **path**. Make it standardise to **path**

iOS response: 'path'
Android response: 'realPath'

**Comment by Janviba911** [comment]
> Please also change for key **path**. Make it standardise to **path**
> 
> iOS response: 'path'
> Android response: 'realPath'

@vivianlys90 
These are two different props, only difference is that iOS is not provide realPath as like Android

**Comment by baronha** [comment]
> In android, we are getting **fileName**, **mine** but in iOS we are getting **filename**, **mime** from response.
> Please make it both same.

Check new version 0.3.0. thanks for your issue

**Comment by Janviba911** [comment]
![image_2021_07_21T11_55_22_524Z](https://user-images.githubusercontent.com/43240917/126485173-f5ff462c-af20-4ddb-bd6f-19985e99d611.png)

@baronha 
After updated version(0.3.2), **filename** prop is still different from iOS and Android

**Comment by James-Firth** [comment]
I also see the same issue that @Janviba911 is having.

When fixed will it be `filename` as the README currently says?
