### ISSUE TITLE
Support for React Native 0.64

### ISSUE THREAD

**Issue by anhquan291** [baronha/react-native-multiple-image-picker#23]
Hi there, hope you're all good.
You know i just upgrade my project to the latest version of RN. However, when compiling I get the following error:

`
   CompileSwift normal x86_64 /Users/xxx/Documents/projectName/mobile/node_modules/@baronha/react-native-multiple-image-picker/ios/MultipleImagePicker.swift
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/xxx/Library/Developer/Xcode/DerivedData/spixp-bvnhzwqgqcverogvbrofgozgqvsx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-46EB2E00021CF0.sh
`

Everything works as intended on RN 0.63.2. Do you plan on supporting 0.64? Thank you so much

**Comment by baronha** [comment]
I am also using RN 0.64 and it still works fine. you can try ```rm -rf ~/Library/Developer/Xcode/DerivedData``` and you can delete ```Podfile.lock``` and re ```pod install````

**Comment by anhquan291** [comment]
> I am also using RN 0.64 and it still works fine. you can try `rm -rf ~/Library/Developer/Xcode/DerivedData` and you can delete `Podfile.lock` and re `pod install`

It works. Thanks a lot. cheer !!!
