### ISSUE TITLE
usedCameraButton prop is not working in Android

### ISSUE THREAD

**Issue by Janviba911** [baronha/react-native-multiple-image-picker#24]
@baronha
usedCameraButton props is not working in android but working fine in iOS. Please check and update as soon as possible.

**Comment by baronha** [comment]
Okay. I will check it out. Thanks for your feedback

**Comment by baronha** [comment]
Check new version 0.3.2.

**Comment by Janviba911** [comment]
Thanks for reply. Now it's working fine
