### ISSUE TITLE
Image path does not start with file://

### ISSUE THREAD

**Issue by ZijianZhang991203** [baronha/react-native-multiple-image-picker#25]
First of all, thank you for developing this amazing library. 
When I works on ios, it works perfectly. However, on android, the image path looks like:
`content:// ` or `storage://` . 
Since I am trying to show image after picking them. So I need to manually add `file://` before the second case.
And I need to convert these uri into path to read these file. Is there any suggestion about this? Thanks!

**Comment by baronha** [comment]
Sorry to say that you have to add ```file://``` manually
