### ISSUE TITLE
Android openPicker return empty response

### ISSUE THREAD

**Issue by vivianlys90** [baronha/react-native-multiple-image-picker#26]
Hi @baronha , I am getting empty response after done select my image using openPicker.

Here is my code:
<img width="454" alt="Screenshot 2021-07-12 at 1 46 33 PM" src="https://user-images.githubusercontent.com/22317616/125237021-93e5dc80-e317-11eb-848c-8f960f16c1fc.png">

And the log return -> `openPicker done:  []`

- Image Picker version: 0.2.10

- React Native version: 0.63

- Platform: Android

**Comment by vivianlys90** [comment]
Found the issue is because of only single image selected. The response should return in array of bean form. But if only single image selected, then the response will return in bean form only. 
Then will return [] when go through this function in library's index.js.
`if (response?.length) {
          resolve(response);
          return;
        }`

I put log in library's index.js, and this is the example of response data I get after done select single image.
![Android](https://user-images.githubusercontent.com/22317616/125252142-9d2c7480-e32a-11eb-8129-7d818be1af1c.png)

**Comment by baronha** [comment]
Well. I updated the new version. Thanks for your contribution.
