### ISSUE TITLE
Lỗi đóng tất cả Modal khi chọn xong thư viện ảnh

### ISSUE THREAD

**Issue by anhquan291** [baronha/react-native-multiple-image-picker#3]
Hi bạn,
Cảm ơn bạn đã chia sẻ thư viện xịn xò này nhá. 

Mình đang bị bug là khi mình mở camera của mình lên (năm trong modal mình dùng rn camera). Từ Camera mình mở thư viện ảnh lên, sau đó mình chọn xong "done" hoặc "cancel" thì đáng ra nó về lại Camera cho mình nhưng nó tắt luôn cả cái modal của Camera mặc dù visible vẫn là true ạ. Không biết mình có làm sai gì không. Mong bạn giúp.

*Update: Android cần remove react-native-image-crop-picker thì chạy được ạ.
Cash trên android khi select hình.

Cảm ơn bạn nhiều ạ

**Comment by baronha** [comment]
Mình nghĩ là do nó đang bị conflict transition với modal của navigation, Bạn thay đổi modal thành kiểu left to right mặc định của iOS cho screen Camera thì mình nghỉ sẽ giải quyết được. Next version chắc mình phải thêm options modal transition dành riêng cho iOS.
Còn lỗi bị conflict với react native image picker thì mình đã solve ở các phiên bản gần đây. Bạn có thể update lên version mới nhất của lib để thử lại. Còn crash khi chọn hình thì mình sẽ tìm hiểu lại thêm (Phiền bạn mô tả chi tiết về lỗi này giúp mình nhé)
Thanks.

**Comment by anhquan291** [comment]
> Mình nghĩ là do nó đang bị conflict transition với modal của navigation, Bạn thay đổi modal thành kiểu left to right mặc định của iOS cho screen Camera thì mình nghỉ sẽ giải quyết được. Next version chắc mình phải thêm options modal transition dành riêng cho iOS.
> Còn lỗi bị conflict với react native image picker thì mình đã solve ở các phiên bản gần đây. Bạn có thể update lên version mới nhất của lib để thử lại. Còn crash khi chọn hình thì mình sẽ tìm hiểu lại thêm (Phiền bạn mô tả chi tiết về lỗi này giúp mình nhé)
> Thanks.

Cảm ơn B nhiều, mình sẽ quay video mà gửi detail thêm nhé thanks bạn.

**Comment by baronha** [comment]
> > Mình nghĩ là do nó đang bị conflict transition với modal của navigation, Bạn thay đổi modal thành kiểu left to right mặc định của iOS cho screen Camera thì mình nghỉ sẽ giải quyết được. Next version chắc mình phải thêm options modal transition dành riêng cho iOS.
> > Còn lỗi bị conflict với react native image picker thì mình đã solve ở các phiên bản gần đây. Bạn có thể update lên version mới nhất của lib để thử lại. Còn crash khi chọn hình thì mình sẽ tìm hiểu lại thêm (Phiền bạn mô tả chi tiết về lỗi này giúp mình nhé)
> > Thanks.
> 
> Cảm ơn B nhiều, mình sẽ quay video mà gửi detail thêm nhé thanks bạn.

Ok Bạn nha.

**Comment by anhquan291** [comment]
Close!!!
