### ISSUE TITLE
How to handle live pictures on iOS?

### ISSUE THREAD

**Issue by jlindberg-oss** [baronha/react-native-multiple-image-picker#32]
I have selected allowedLivePhotos=true.

Live photos showing fine in the image picker.
But after I select, how do I show the l live photo within react native, or get the full path for uploading?

Right now only getting HEIC which seems to be just the image.

**Comment by jlindberg-oss** [comment]
I've tested both live and non-live photos and the live photo HEIC is always at least twice as big.
So hopefully the HEIC is really storing the video too.  But I haven't figured out how to show it yet.

**Comment by baronha** [comment]
You can try (this library)[https://github.com/NarekChang/react-native-livephoto] to showing the live photos.

**Comment by jlindberg-oss** [comment]
@baronha thanks.  that one is requiring `imgUri` and `videoUri` for the live photo.
But when I have a live photo, `react-native-multiple-image-picker` is only showing one file (an image).  How to get both `imgUri` and `videoUri`?

**Comment by baronha** [comment]
> @baronha thanks. that one is requiring `imgUri` and `videoUri` for the live photo.
> But when I have a live photo, `react-native-multiple-image-picker` is only showing one file (an image). How to get both `imgUri` and `videoUri`?

I have re-examined the problem. This is a bug that exists on iOS. I accidentally converted a LivePhoto to JPEG. I will find a way to fix it in the next versions.

**Comment by jlindberg-oss** [comment]
Thank you!  I will be excited to test any fix.

**Comment by eldynguyen1204** [comment]
fix bug đi Bảo ơi! @baronha

**Comment by dannyxu2015** [comment]
Does it fixed now ? @baronha
