### ISSUE TITLE
Slow at the first opening

### ISSUE THREAD

**Issue by anhquan291** [baronha/react-native-multiple-image-picker#33]
Hi Ha,

It's been so nice using your lib. However, it opens really slow on real device when the app is reopened. Any suggestions please? Thank you.

Have a great week and stay safe !

https://user-images.githubusercontent.com/17813202/127124521-57c55d91-5896-4704-b4c3-242d9b4a2561.mp4

**Comment by baronha** [comment]
I can't see the video you sent. But I have a question: are you running on a real device while connected to the XCode debugger? If this is true then you don't need to worry as it only affects while you're programming (and only happens the first time you open it). If not, please resend the video to me.

**Comment by anhquan291** [comment]
> I can't see the video you sent. But I have a question: are you running on a real device while connected to the XCode debugger? If this is true then you don't need to worry as it only affects while you're programming (and only happens the first time you open it). If not, please resend the video to me.

Hi Ha, thanks for taking your time.

**Comment by baronha** [comment]
Show me your code. I don't think I can fix this. Because I never had this situation when I publish to Testflight(Including the official version on the AppStore). I can only think that this is coming from the permission query.

**Comment by anhquan291** [comment]
> Show me your code. I don't think I can fix this. Because I never had this situation when I publish to Testflight(Including the official version on the AppStore). I can only think that this is coming from the permission query.
> 
> 

Let me check it again. Will keep you posted. Thank you so much

**Comment by anhquan291** [comment]
@baronha  hi, forgot to attached the code :D. Here it is. Everything works fine on Simulator.

`  const images = await MultipleImagePicker.openPicker({
    isPreview: false,
    numberOfColumn: 4,
    selectedColor: Colors.PRIMARY_LIGHT_COLOR,
    mediaType: 'all',
    maxVideoDuration: 120,
    maxVideo: videoCount,
    maxSelectedAssets: mediaCount,
    selectedAssets: [],
    isExportThumbnail: true,
  });`

**Comment by baronha** [comment]
Your code is correct. Maybe this problem I will experience more to find a solution.
