### ISSUE TITLE
Undefined symbol: (extension in UIKit):__C.UIAction.init(title: Swift.String, image: __C.UIImage?, identifier: __C.UIActionIdentifier?, discoverabilityTitle: Swift.String?, attributes: __C.UIMenuElementAttributes, state: __C.UIMenuElementState, handler: (__C.UIAction) -> ()) -> __C.UIAction

### ISSUE THREAD

**Issue by uplamartya** [baronha/react-native-multiple-image-picker#37]
I have tried cleaning up xcoe cache, but that didn't fix the issue for me, also I am using xcode 12.5.1, attaching Library search path snapshot below
<img width="508" alt="Screenshot 2021-08-21 at 12 13 26 PM" src="https://user-images.githubusercontent.com/47631015/130313234-6b048fcb-19ed-4298-9d33-1b0ee60f5045.png">

Error I am getting 
<img width="862" alt="Screenshot 2021-08-21 at 12 16 27 PM" src="https://user-images.githubusercontent.com/47631015/130313311-4d0aa908-7435-4638-8dee-18a72a63348e.png">

**Comment by baronha** [comment]
You can check [here](https://github.com/baronha/react-native-multiple-image-picker/raw/main/files/resolve-error-iOS.png)
