### ISSUE TITLE
Ios return 2 file:// in path

### ISSUE THREAD

**Issue by hungdev** [baronha/react-native-multiple-image-picker#40]
I think it should be one `file://`
and android is fine
![image](https://user-images.githubusercontent.com/12009276/132949604-ef323211-2d61-4bfe-8f50-4fb679a6283c.png)

**Comment by htactive-cuongnm** [comment]
i fixed = replace :))

**Comment by hungdev** [comment]
Yes i fixed it by using replace and  if else to check condition android or ios platform. Because only ios get this error. But it would be great if the lib returned available
