### ISSUE TITLE
Execution failed for task ':baronha_react-native-multiple-image-picker:compileDebugKotlin'.

### ISSUE THREAD

**Issue by htactive-cuongnm** [baronha/react-native-multiple-image-picker#44]
- i have issue when i build app android like this ... so i need help plz
![image](https://user-images.githubusercontent.com/51102593/135081103-aa67357c-fc0b-4bf6-bb10-6123187b2ad4.png)

version :  "@baronha/react-native-multiple-image-picker": "^0.4.5",
"react-native": "0.63.4",

**Comment by baronha** [comment]
you can check the new setup in [Android](https://github.com/baronha/react-native-multiple-image-picker#android).

**Comment by htactive-cuongnm** [comment]
> you can check the new setup in [Android](https://github.com/baronha/react-native-multiple-image-picker#android).

yes i know it ... but i fixed error = down version jdk android 16 -> 11  :))

**Comment by methineeinkan** [comment]
same

**Comment by duongbui234** [comment]
I also got the same error .I downgraded the version to ver11 but still no success
![image](https://user-images.githubusercontent.com/67871183/223988137-9f842f82-57e7-4bae-b0c9-6d5e369dabe9.png)
"@baronha/react-native-multiple-image-picker": "^0.4.8",
"react-native": "0.66.0",
