### ISSUE TITLE
Does it work with expo?

### ISSUE THREAD

**Issue by kylemarimon** [baronha/react-native-multiple-image-picker#5]
Hi there, does your code support react native projects built using [Expo](https://expo.io/)?

**Comment by baronha** [comment]
I do not currently have plans to support Expo. If you can do that, the Expo user and I will be very grateful to you.

**Comment by Hirbod** [comment]
This library works flawlessly on expo using a custom dev client. I just installed it a couple of minutes ago.
Just had to make sure to add some permissions using the app.config.js and call `expo prebuild`.
