### ISSUE TITLE
After selecting an image in the simulator, it doesn't close.

### ISSUE THREAD

**Issue by dkahdwk** [baronha/react-native-multiple-image-picker#51]
### Steps to Reproduce
1. Operate MultipleImagePicker.openPicker.
2. The image selection modal opens.
3. After selection, it cannot proceed to the next without any errors.
4. But, it works normally on real devices.

- It doesn't go to the next step.
<img width="202" alt="스크린샷 2021-10-29 오후 12 45 59" src="https://user-images.githubusercontent.com/56759331/139373408-d282910e-0e0b-4dd5-a6cb-c654b8126189.png">

### code
```
    // handler
    const handleImagePicker = async () => {
        try {
            const image = await MultipleImagePicker.openPicker({
                // selectedAssets: images,
                usedCameraButton: true,
                isExportThumbnail: true,
                maxVideo: 1,
                maxSelectedAssets: 4,
                doneTitle: '완료',
                cancelTitle: '취소',
                tapHereToChange: '변경하려면 여기를 누르세요.',
                singleSelectedMode: false
                // selectedColor: '#f9813a',
            });
        } catch (e) {
            console.log('error', e);
        } finally {
            console.log('finally')
        }
    };
```

### Demo
Since it is a corporate project, it is not possible to share a reproduction of the demo...

### Environment

* react-native-multiple-image-picker: 0.4.7
* react-native version: 0.64.2
* iOS/Android/Windows version: ios simulator
* Does this reproduce on a debug build or release build? yes
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by dkahdwk** [comment]
> > @baronha I need your help! Am I the only one who has that issue?
> 
> @dkahdwk I cannot reproduce this on my simulator. Try upgrading to the latest version `0.4.8`. If this problem persists. Please leave a message to let me know.

I upgraded the version, but there is still an issue. (xcode 13.0, iPhone12 - IOS15.0)

**Comment by dkahdwk** [comment]
> > @baronha I need your help! Am I the only one who has that issue?
> 
> @dkahdwk I cannot reproduce this on my simulator. Try upgrading to the latest version `0.4.8`. If this problem persists. Please leave a message to let me know.

I found out something new! This problem occurs in MacBook m1. MacBook Intel does not cause problems in the same environment. I hope it helps and I hope this problem will be resolved soon.

**Comment by baronha** [comment]
> > > @baronha I need your help! Am I the only one who has that issue?
> > 
> > 
> > @dkahdwk I cannot reproduce this on my simulator. Try upgrading to the latest version `0.4.8`. If this problem persists. Please leave a message to let me know.
> 
> I found out something new! This problem occurs in MacBook m1. MacBook Intel does not cause problems in the same environment. I hope it helps and I hope this problem will be resolved soon.

@dkahdwk  Wow. I can't reproduce this error at all on Macbook M1. Because I don't have 🥺. Probably with the help of the other members.

**Comment by denisamalgama** [comment]
Same issue here!

**Comment by kimrborja** [comment]
same issue, any news here?

**Comment by nain93** [comment]
Even if it's an m1, if I build it in xcode and use a real device it works fine

**Comment by Mayur552-choudhary** [comment]
I'm also facing same issue, any solution for this ?

**Comment by dkahdwk** [comment]
> I'm also facing same issue, any solution for this ?

There is no solution. Another library could be a way

**Comment by nain93** [comment]
아이폰에서 xcode로 릴리즈 빌드해서 봐도 안되나요?? @dkahdwk

**Comment by dkahdwk** [comment]
> 아이폰에서 xcode로 릴리즈 빌드해서 봐도 안되나요?? @dkahdwk 

저 당시에는 안됐었어요!
여러 이슈가 있어서 다른거로 교체하시는걸 추천드려요

**Comment by kimrborja** [comment]
Well, they say it works on actual device... will just trust that. I'll have to deploy on testflight to see. Thanks!

**Comment by Mayur552-choudhary** [comment]
I created fresh project then try It's working, after I install react-native-maps and update podfile then again loading issue.


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'testApp' do
  config = use_native_modules!
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'testAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
end

**Comment by ErangaD** [comment]
Same issue on ios simulator (iphone13). 
But works on a real device.

**Comment by MiteshKalal7** [comment]
I got same error, it was working before suddenly now it is stuck at "Please wait..." on macbook pro M1 and iphone 13 simulator with ios 13.0... working fine on real iphone device.

**Comment by MiteshKalal7** [comment]
maybe the issue is getting because of this code

installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        end
      end
      
  but when i remove it i got another errors :(

**Comment by ErangaD** [comment]
This issue went away after updating xcode to latest version (14.3) for me.

**Comment by MiteshKalal7** [comment]
@ErangaD yeah now i think its time to update 14.0 to 14.3 :), will try and let you know
