### ISSUE TITLE
value doesn't exist in options.  Where's this coming from ?

### ISSUE THREAD

**Issue by EddStrickland** [baronha/react-native-multiple-image-picker#55]
https://github.com/baronha/react-native-multiple-image-picker/blob/389cd75411e45f0b744c8da163fcd6904853af43/example/src/App.js#L14

is this a bug or an option missing from the options type?

**Comment by baronha** [comment]
> https://github.com/baronha/react-native-multiple-image-picker/blob/389cd75411e45f0b744c8da163fcd6904853af43/example/src/App.js#L14
> 
> is this a bug or an option missing from the options type?

Export thumbnail image for Video type.

**Comment by EddStrickland** [comment]
sure but within the example you've got it as a single image file type for the multi file upload, it seems like this is trying to cover both things with one implementation however the MultipleImagePicker is where you're getting your options type from not video upload.  so either this needs to have those types included (see my other issue) or these need to be split out to make sure it doesn't cause errors when rendering the MultipleImagePicker
