### ISSUE TITLE
Extreme slow "export"

### ISSUE THREAD

**Issue by hirbod** [baronha/react-native-multiple-image-picker#58]
Running on my iPhone 13 Pro Max, selecting 3 videos (each between 10 to 50 seconds) takes a whapping 55 seconds until finished (Stucking on "Please wait"). Whats wrong here? Is there some magic over the bridge happening?

Usally the selection should be instant.

RN 0.64.3
Newest library version.

**Comment by Hirbod** [comment]
No, I am not using iCloud Photos nor iCloud Storage
