### ISSUE TITLE
[TypeError: null is not an object (evaluating 'MultipleImagePicker.openPicker')]  in ios

### ISSUE THREAD

**Issue by Seu07** [baronha/react-native-multiple-image-picker#6]
I configured already:
1 . <key>NSCameraUsageDescription</key>
    <string>1</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string></string>
    <key>NSPhotoLibraryAddUsageDescription</key>
    <string>1</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>1</string>
2. change this "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" to "$(TOOLCHAIN_DIR)/usr/lib/swift-5.3/$(PLATFORM_NAME)"
 
still not work on ios ("react-native": "^0.64.0"). but android work as a charm. thanks)

**Comment by Seu07** [comment]
add swift file and header configure as tutorial but react-native run-ios have no success. anyway this plugin is so cool. hope near the future will fix and work both ios and android

**Comment by baronha** [comment]
Have you tried to run pod install in the ios folder? 
And then build the app via Xcode instead of ``run-ios`` in Terminal.

**Comment by Seu07** [comment]
yes I did. but no success

**Comment by Janviba911** [comment]
I am also facing same issue @baronha

**Comment by wonderer007** [comment]
I am having same issue on android

**Comment by baronha** [comment]
> I am having same issue on android

Are you upgrade to new version v1.1.2?
