### ISSUE TITLE
[bug][iOS] Path return has doubled "file://"

### ISSUE THREAD

**Issue by Hirbod** [baronha/react-native-multiple-image-picker#61]
While I do not have any issues currently, the path returned looks like this:

```
   "path": "file://file:///private/var/mobile/Containers/Data/Application/710BA300-2DAE-4001-B904-4E2206F11A1F/tmp/IMG_7403.JPG",
```

So "file://" is doubled. My libraries seem to automatically fix this or be able to work with it (or iOS is smart enough) but this should not be doubled, right?

**Comment by Janviba911** [comment]
@Hirbod 
Please try this below code
path = path.replace('file://', '')

**Comment by Hirbod** [comment]
I know how to patch that in JS @Janviba911, but thanks :D

**Comment by Janviba911** [comment]
> I know how to patch that in JS @Janviba911, but thanks :D.
> And your suggestion would actually break, because it would replace both file:// occurrences

@Hirbod 
Ok great!!! My suggestion would work well too because It replace first occurrence only

**Comment by baronha** [comment]
I just removed it in version 4.0.10.
But I think you should add file:// prefix in javascript code. Its difference comes from memory

<img width="756" alt="Screen Shot 2022-01-16 at 15 12 49" src="https://user-images.githubusercontent.com/23580920/149652405-ecd8e601-59b9-4524-aaf8-0483fafbcf20.png">
<img width="755" alt="Screen Shot 2022-01-16 at 15 11 13" src="https://user-images.githubusercontent.com/23580920/149652400-11c96f91-2fb2-42b7-b4ec-76431959ad5b.png">

**Comment by ertucaglar** [comment]
I guess this problem still persists

"file://file:///Users/ertucaglar/Library/Developer/CoreSimulator/Devices..."
