### ISSUE TITLE
[Android] Bị reload lại App sau khi vào app info để bật quyền lại.

### ISSUE THREAD

**Issue by huyth-2224** [baronha/react-native-multiple-image-picker#65]
Vấn đề ở Android
Xin chào, hiện tại mình có sử dụng thư viện này. Tuy nhiên nếu người dùng lúc đầu từ chối cấp quyền truy cập thư viện ảnh. Sau đó người dùng vẫn ở trong app mình. và cho  nhấn nút home để app xuống background để vào phần setting để bật quyền lại. Và quay trở lại app thì app bị reload lại ạ. Thay vì vẫn ở màn hình cuối mà người dùng đang dùng.

Cám ơn bạn, nếu có phương án giải quyết cho mình ạ

**Comment by baronha** [comment]
> Vấn đề ở Android Xin chào, hiện tại mình có sử dụng thư viện này. Tuy nhiên nếu người dùng lúc đầu từ chối cấp quyền truy cập thư viện ảnh. Sau đó người dùng vẫn ở trong app mình. và cho nhấn nút home để app xuống background để vào phần setting để bật quyền lại. Và quay trở lại app thì app bị reload lại ạ. Thay vì vẫn ở màn hình cuối mà người dùng đang dùng.
> 
> Cám ơn bạn, nếu có phương án giải quyết cho mình ạ

Em đoán có lẽ là anh đang sử dụng iOS. Hành vi người dùng đã bị thay đổi với cấp quyền truy cập hình ảnh đối với mọi ứng dụng. Hệ điều hành buộc phải reload lại lại app. Điều này xảy ra với cả Facebook hoặc một số ứng dụng khác cần quyền hình ảnh. Điều này thật sự bất tiện

**Comment by baronha** [comment]
Em sẽ xem xét lại điều này. Nếu nó là bắt buộc đối với hệ điều hành thì em cũng xin chịu

**Comment by huyth-2224** [comment]
dạ. nếu là bắt buộc thì đành chịu ạ

**Comment by baronha** [comment]
Rất tiếc vì đây là do hệ điều hành quyết định ạ.
