### ISSUE TITLE
Cant Upload Image

### ISSUE THREAD

**Issue by itsnyx** [baronha/react-native-multiple-image-picker#69]
after reading the files from gallery i want to upload it using fetch method to my amazon server and i path the whole image object in the body but the file i get in server is 0 bytes

the image file is the first object in the returned list by the image pickers. 

`    await fetch(base_url, {
      method: 'PUT',
      headers: {
        'Content-Type': 'multipart/form-data',
      },
      body: image,
    });`

**Comment by itsnyx** [comment]
i fixed this issue by passing the path field of the image file to a blob function

`  const getBlob = async fileUri => {
    const resp = await fetch(fileUri);
    const imageBody = await resp.blob();
    return imageBody;
  };`

**Comment by BrightDev1110** [comment]
+1 same
