### ISSUE TITLE
Camera button not working

### ISSUE THREAD

**Issue by mparramont** [baronha/react-native-multiple-image-picker#7]
Hi again!

First of all, thanks a lot for all the work on this great library 🎉 

I'm facing this issue where pressing the Camera button on the image picker does nothing:
<img src="https://user-images.githubusercontent.com/636075/116208047-14faf200-a773-11eb-93d7-2668b3f219fe.png" width=360/>

I'm using a basic call for opening the picker:
```javascript
  async handlePress() {
    await MultipleImagePicker.openPicker({ mediaType: 'image' })
  }
```

I reviewed all the documentation and found no way to configure its behaviour.

Would it be possible to get some help about this? Thanks!

**Comment by baronha** [comment]
The camera only works on real devices. Have you tried it yet?

**Comment by mparramont** [comment]
Ohh I see! I'll try on a real device, thanks!
