### ISSUE TITLE
IOS error [this class is not key value coding-compliant for the key localIdentifier.' was thrown while invoking openPicker on target MultipleImagePicker with params]

### ISSUE THREAD

**Issue by Eric0117** [baronha/react-native-multiple-image-picker#73]
Exception '[<__NSCFNumber 0xd9925f6dc86b5d23> valueForUndefinedKey:]: this class is not key value coding-compliant for the key localIdentifier.' was thrown while invoking openPicker on target MultipleImagePicker with params (
 
{
        allowedAlbumCloudShared = 0;
        allowedLivePhotos = 1;
        allowedPhotograph = 1;
        allowedVideo = 1;
        allowedVideoRecording = 0;
        autoPlay = 1;
        cancelTitle = Cancel;
        deselectMessage = Deselect;
        doneTitle = Done;
        emptyMessage = "No albums";
        haveThumbnail = 1;
        isCrop = 1;
        isCropCircle = 1;
        isExportThumbnail = 1;
        isPreview = 1;
        maxSelectedAssets = 20;
        maxVideo = 1;
        maxVideoDuration = 60;
        maximumMessage = "You have selected the maximum number of media allowed";
        maximumMessageTitle = Notification;
        maximumVideoMessage = "You have selected the maximum number of video allowed";
        mediaType = all;
        messageTitleButton = OK;
        muteAudio = 1;
        numberOfColumn = 3;
        preventAutomaticLimitedAccessAlert = 1;
        selectMessage = Select;
        selectedAssets =         (
            1,
            2,
            3
        );
        selectedColor = "#FB9300";
        singleSelectedMode = 0;
        tapHereToChange = "Tap here to change";
        thumbnailHeight = 422;
        thumbnailWidth = 195;
        usedCameraButton = 0;
        usedPrefetch = 0;
    },
    5184,
    5185
)

I did Privacy Description in info.plist and pod install

And use example source

**Comment by GoDeepBlue** [comment]
I am having the same issue / error. openPicker works fine the first call, however, the second call produces the error below. Also, Privacy Description is in info.plist.

Exception '[<__NSCFString 0x6000024e6b10> valueForUndefinedKey:]: this class is not key value coding-compliant for the key localIdentifier.' was thrown while invoking openPicker on target MultipleImagePicker with params (
        {
        allowedAlbumCloudShared = 0;
        allowedLivePhotos = 1;
        allowedPhotograph = 1;
        allowedVideo = 1;
        allowedVideoRecording = 0;
        autoPlay = 1;
        cancelTitle = Cancel;
        deselectMessage = "Long press";
        doneTitle = Done;
        emptyMessage = "No pics";
        haveThumbnail = 1;
        isCrop = 0;
        isCropCircle = 0;
        isExportThumbnail = 1;
        isPreview = 1;
        maxSelectedAssets = 3;
        maxVideo = 20;
        maxVideoDuration = 60;
        maximumMessage = "You have selected the maximum number of media allowed";
        maximumMessageTitle = "Max pictures selected";
        maximumVideoMessage = "You have selected the maximum number of video allowed";
        mediaType = image;
        messageTitleButton = OK;
        muteAudio = 1;
        numberOfColumn = 3;
        preventAutomaticLimitedAccessAlert = 1;
        selectMessage = "Long press";
        selectedAssets =         (
            "file:///Users/james/Library/Developer/CoreSimulator/Devices/406FD55B-F186-4DA1-8888-4995F0EF45E5/data/Containers/Data/Application/440467AC-88F5-495D-97AC-6E5F18A76A85/tmp/IMG_0001.JPG",
            "file:///Users/james/Library/Developer/CoreSimulator/Devices/406FD55B-F186-4DA1-8888-4995F0EF45E5/data/Containers/Data/Application/440467AC-88F5-495D-97AC-6E5F18A76A85/tmp/IMG_0111.HEIC",
            "file:///Users/james/Library/Developer/CoreSimulator/Devices/406FD55B-F186-4DA1-8888-4995F0EF45E5/data/Containers/Data/Application/440467AC-88F5-495D-97AC-6E5F18A76A85/tmp/IMG_0003.JPG"
        );
        selectedColor = "#FB9300";
        singleSelectedMode = 0;
        tapHereToChange = "Tap here to change";
        thumbnailHeight = 466;
        thumbnailWidth = 215;
        usedCameraButton = 0;
        usedPrefetch = 0;
    },
    25430,
    25431
)
callstack: (
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180437040 -[NSException init] + 0
	3   Foundation                          0x0000000180b1d1f0 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 188
	4   Foundation                          0x0000000180b1c114 -[NSObject(NSKeyValueCoding) valueForKey:] + 300
	5   Skoova                              0x0000000106f89c68 $s34react_native_multiple_image_picker19MultipleImagePickerC20handleSelectedAssets12selectedListySo7NSArrayC_tFSbypXEfU_ + 164
	6   libswiftCore.dylib                  0x000000018bd57148 $sSTsE6filterySay7ElementQzGSbACKXEKF + 504
	7   Skoova                              0x0000000106f8956c $s34react_native_multiple_image_picker19MultipleImagePickerC20handleSelectedAssets12selectedListySo7NSArrayC_tF + 236
	8   Skoova                              0x0000000106f893bc $s34react_native_multiple_image_picker19MultipleImagePickerC16setConfiguration33_5E44583212DB8F5EDF173F9172EB7317LL7options7resolve6rejectySo12NSDictionaryC_yypSgcySSSg_ALs5Error_pSgtctF + 17328
	9   Skoova                              0x0000000106f82190 $s34react_native_multiple_image_picker19MultipleImagePickerC04openH07options7resolve6rejectySo12NSDictionaryC_yypSgcySSSg_AKs5Error_pSgtctF + 96
	10  Skoova                              0x0000000106f8242c $s34react_native_multiple_image_picker19MultipleImagePickerC04openH07options7resolve6rejectySo12NSDictionaryC_yypSgcySSSg_AKs5Error_pSgtctFTo + 204
	11  CoreFoundation                      0x000000018043d6c0 __invoking___ + 144
	12  CoreFoundation                      0x000000018043aa44 -[NSInvocation invoke] + 276
	13  CoreFoundation                      0x000000018043acdc -[NSInvocation invokeWithTarget:] + 60
	14  Skoova                              0x0000000106025508 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1796
	15  Skoova                              0x0000000106029594 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1688
	16  Skoova                              0x0000000106028d30 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128
	17  Skoova                              0x0000000106028ca4 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	18  libdispatch.dylib                   0x0000000180132ee4 _dispatch_call_block_and_release + 24
	19  libdispatch.dylib                   0x0000000180134708 _dispatch_client_callout + 16
	20  libdispatch.dylib                   0x000000018013c77c _dispatch_lane_serial_drain + 776
	21  libdispatch.dylib                   0x000000018013d3dc _dispatch_lane_invoke + 392
	22  libdispatch.dylib                   0x0000000180149608 _dispatch_workloop_worker_thread + 768
	23  libsystem_pthread.dylib             0x00000001b1834878 _pthread_wqthread + 284
	24  libsystem_pthread.dylib             0x00000001b183363c start_wqthread + 8
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by GoDeepBlue** [comment]
Is was self inflicted ... In the openPicker options I was passing a string to the selectedAssets property versus an array.
