### ISSUE TITLE
The library is caching a damaged video after killing the while loading

### ISSUE THREAD

**Issue by fhasni** [baronha/react-native-multiple-image-picker#74]
We have an upload media feature where we used `react-native-multiple-image-picker`, We figured out that some uploaded videos through this library on iOS are damaged. I checked the source code and I found that it is using a caching before providing a link to the cached media not of the original file.

The scenario to get damaged file is:
- Select video
- Then kill the app while loading
- Open the app again try to select the same video
- Bug: Video damaged

**Comment by baronha** [comment]
Do you have a video description for this issue?
