### ISSUE TITLE
After selecting image crop screen not opening on Android too

### ISSUE THREAD

**Issue by pratik-complitech** [baronha/react-native-multiple-image-picker#75]
const openMultiplePicker = async () => {
        console.log("openMultiplePicker")
        try {
          const response = await MultipleImagePicker.openPicker({
            isExportThumbnail: true,
            mediaType: 'image',
            usedCameraButton: false,
            isCrop: true,
            isCropCircle: true,
          });
          console.log('response: ', response);
          setImages(response);
        } catch (e) {
          console.log("error is :", e.code, e.message);
        }
      };

Cropping functionality even not working on Android ?

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!
