### ISSUE TITLE
Loading image with is synched from Mac is failed.

### ISSUE THREAD

**Issue by Ella-noncelab** [baronha/react-native-multiple-image-picker#79]
https://support.apple.com/guide/mac-help/mchl4af095d3/mac

We can synched photos from mac to iphone following upper link document. Then I can see "My Mac" section in my iphone photo applications as you can see in this image.
![IMG_5653](https://user-images.githubusercontent.com/73803777/191201840-477b707d-3ff7-410e-9de6-0b5f34279bcb.PNG)

And if I choose the image, I am stuck in this screen seeing "Please wait" loading animation.
![IMG_5654](https://user-images.githubusercontent.com/73803777/191201892-3a1d5b0d-806f-4aea-9cb5-5a091e6b7e58.PNG)

Could you solve this? ㅠㅠ

**Comment by fukemy** [comment]
did you get any log, may be some wrong happen when write file to app folder

**Comment by baronha** [comment]
Check new version: [2.0](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/2.0)
Docs: https://baronha.github.io/react-native-multiple-image-picker/
