### ISSUE TITLE
Can not display the picked photos

### ISSUE THREAD

**Issue by anbkit** [baronha/react-native-multiple-image-picker#8]
Hi, that's a great package. But I have a problem when using it, after picked the photos, the photos are not displayed. I think the problem is those photos are stored on iCloud. How can I fix the problem?
Thanks.

**Comment by baronha** [comment]
Yah. iCloud Photo is the cause. I am planning on support for iCloud Photo. It would be great if you could help me with that.

**Comment by anbkit** [comment]
I wrote code below to solve the problem and it is working correctly.  
```
let path = photo.path;
      if(Platform.OS==='ios'){
          path = 'ph://'+photo.localIdentifier;
      }
```

**Comment by baronha** [comment]
> I wrote code below to solve the problem and it worked correctly.
> 
> ```
> let path = photo.path;
>       if(Platform.OS==='ios'){
>           path = 'ph://'+photo.localIdentifier;
>       }
> ```

I added a loading view to handle downloading photos from iCloud in version 0.4.1
