### ISSUE TITLE
Getting error while running Android app

### ISSUE THREAD

**Issue by anilchrishan** [baronha/react-native-multiple-image-picker#80]
node_modules/@baronha/react-native-multiple-image-picker/android/src/main/java/com/reactnativemultipleimagepicker/GlideEngine.kt: (43, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.

**Note: Could you add  iOS and Android version compatibility in document?**

**Comment by sagar2701** [comment]
getting same error

**Comment by hm1061998** [comment]
try modifying as follows:


`diff --git a/node_modules/@baronha/react-native-multiple-image-picker/android/build.gradle b/node_modules/@baronha/react-native-multiple-image-picker/android/build.gradle
index fcb659d..01c2341 100644
--- a/node_modules/@baronha/react-native-multiple-image-picker/android/build.gradle
+++ b/node_modules/@baronha/react-native-multiple-image-picker/android/build.gradle
@@ -1,6 +1,6 @@
 buildscript {
   // Buildscript is evaluated before everything else so we can't use getExtOrDefault
-  def kotlin_version = "1.4.32"
+  def kotlin_version = "1.6.0"
 
   repositories {
     google()
@@ -120,7 +120,7 @@ repositories {
   }
 }
 
-def kotlin_version = "1.4.32"
+def kotlin_version = "1.6.0"
 
 dependencies {
   // noinspection GradleDynamicVersion
`

**Comment by baronha** [comment]
solved it!

**Comment by sym900728** [comment]
not worked
