### ISSUE TITLE
Android - App crash khi sử dụng các function của react-native-image-crop-picker.

### ISSUE THREAD

**Issue by dungdt-itealteam** [baronha/react-native-multiple-image-picker#81]
`Hi` bạn.

Hiện mình đang sử dụng lib của bạn. Lib thật sự rất ok nhưng hiện tại mình đang bị 1 vấn đề đó là mình có sử dụng với 1 thư viện khác là [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker).

Với bên ios thì mọi việc chạy rất ok nhưng với android thì khi build  => bị lỗi, Mình đã p update trong file AndroidManifest.xml với giá trị như sau:

```
<activity
            android:screenOrientation="portrait"
            android:name="com.yalantis.ucrop.UCropActivity"
            tools:remove="android:theme"
            android:exported="false"
        />
```

thì android đã build và run đc ok nhưng khi mình dùng các hàm của react-native-image-crop-picker thì app bị crash. (Sau khi chọn ảnh hoặc sau khi chụp ảnh nhấn ok).

Bạn có thể cho mình hướng để xử lý đc ko ạ? Cảm ơn bạn rất nhiều

**Comment by baronha** [comment]
Bạn có thể upgrade lên phiên bản mới nhất của thư viện (phiên bản hiện tại là 1.0.0). Trong phiên bản này đã có tính năng `crop-image`. Bạn có thể xoá hẳn luôn [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) cũng được.
`crop-image` chỉ sử dụng được khi `singleSelectedMode = true` và `isCrop = true`
