### ISSUE TITLE
Getting error on android

### ISSUE THREAD

**Issue by sym900728** [baronha/react-native-multiple-image-picker#83]
e: C:/Users/SYM/.gradle/caches/transforms-3/03d62fff81a11b11b4df46fcfa6f6dc7/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

**Comment by itsnyx** [comment]
@sym900728 I think latest build fixes this issue if not you can temporarily use my fork to fix the build error.

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!
