### ISSUE TITLE
i run this module on ios not running

### ISSUE THREAD

**Issue by samsularifin05** [baronha/react-native-multiple-image-picker#84]
i am running this module on ios it is not running. and when i press the photo upload button, the app exits immediately.
but on android it runs fine.
What is wrong ???

try {
      const options = {
        selectedColor: colors.primary,
        selectedAssets: foto,
        isExportThumbnail: true,
        maxVideo: 1,
        usedCameraButton: true,
        isCrop: true,
        isCropCircle: true,
        mediaType: 'image',
      };
      const response = await MultipleImagePicker.openPicker(options);
      setFoto(response);
    } catch (e) {
      console.log(e)
    }

My Packgae Json

  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-slider-banner": "^1.0.3",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-share": "^8.0.0",
    "react-native-svg": "^13.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-swipeable": "^0.6.0",
    "@baronha/react-native-multiple-image-picker": "^0.4.13",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.3",
    "firebase": "^9.13.0"
  },

**Comment by baronha** [comment]
Please try:
```js
import { openPicker } from '@baronha/react-native-multiple-image-picker';
// ...
const response = await openPicker(options);
```

Lastest version: [1.1.2](https://github.com/baronha/react-native-multiple-image-picker/releases/tag/1.1.2)
