### ISSUE TITLE
When update PictureSelector v3.10.7 to support API33?

### ISSUE THREAD

**Issue by huyth-2224** [baronha/react-native-multiple-image-picker#86]
Hi guy,

Do you have plan to upgrade PictureSelector?
https://github.com/LuckSiege/PictureSelector/releases/tag/v3.10.7

Thanks,
Huy

**Comment by ko-devHong** [comment]
you can resolve my fork package
```
yarn add @ko-devhong/react-native-multiple-image-picker
```

**Comment by huyth-2224** [comment]
@ko-devHong Thanks, I will check it.

**Comment by ko-devHong** [comment]
@huyth-2224 Please see my revised answer.

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!
