### ISSUE TITLE
Support Android 13

### ISSUE THREAD

**Issue by Manikanta-20** [baronha/react-native-multiple-image-picker#87]
This library will support android 13?

I'm getting Read memory card access denied .. I already given permission still getting same

**Comment by ko-devHong** [comment]
you can resolve my fork package
```
yarn add @ko-devhong/react-native-multiple-image-picker
```

**Comment by ko-devHong** [comment]
It can be solved using my forkpackage
```
yarn add @ko-devhong/react-native-multiple-image-picker
```

**Comment by kush4999** [comment]
I'm getting error Read memory card access denied in "baronha/react-native-multiple-image-picker". I already taken run time permission from users still getting same any one have any solution?

//taking permission
![image1](https://user-images.githubusercontent.com/62102982/221106681-d325b015-4808-47dc-9cb7-46bc4b81ea81.jpg)

//permission granted screenshot in app settings
![image2](https://user-images.githubusercontent.com/62102982/221106790-23cb1ad5-f155-4f12-b9dc-e3f1bc034029.jpg)

//issue faced
![issue_image](https://user-images.githubusercontent.com/62102982/221106870-a20543bb-2629-4930-87e1-f112483d45ca.jpg)

**Comment by kush4999** [comment]
@ko-devHong answer works in my case. Thanks @ko-devHong

**Comment by itsnyx** [comment]
@ko-devHong  i tried to use your fork but i got following error while installing it :

```
error fsevents@2.3.2: The platform "win32" is incompatible with this module.
error Found incompatible module.
```

can you update your fork to fix this?

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!
