### ISSUE TITLE
maxVideoDuration is recording for 60 seconds 

### ISSUE THREAD

**Issue by devilabhi** [baronha/react-native-multiple-image-picker#90]
I passed 31 value in maxVideoDuration i.e
`maxVideoDuration:31`
It is showing the videos that are of max 30 seconds but while recording from camera it is not recording for 30 seconds. Any help is appreciated.
Thanks

**Comment by itsnyx** [comment]
hello, this is because default duration is set to 60 just add the maxDuration field to fix it 

`   const response = await MultipleImagePicker.openPicker({
      usedCameraButton: false,
      isExportThumbnail: true,
      isPreview: true,
      mediaType: 'all',
      maxSelectedAssets: 1,
      maxVideoDuration: 1200, // change this with your choice
    });
`

**Comment by devilabhi** [comment]
Hi @itsnyx,
 Please check my comment that is first in this page i.e. I set maxVideoDuration: 31

**Comment by baronha** [comment]
hi @devilabhi  Does your issue still persist?
