### ISSUE TITLE
Read access denied for android 13 (API 33).

### ISSUE THREAD

**Issue by sagar17-create** [baronha/react-native-multiple-image-picker#92]
upgrade the package for Android 13 , make it compatible regarding reading the images . 
There is new update for permission regarding android 13 READ_MEDIA_IMAGES . 

Please update it !

https://developer.android.com/about/versions/13/behavior-changes-13

**Comment by kush4999** [comment]
I face the issues regarding read memory card access denied in 'baronha/react-native-multiple-image-picker' package have any one solve these issue?

**Comment by kush4999** [comment]
Uninstall ""baronha/react-native-multiple-image-picker"" library from the project install "@ko-developerhong/react-native-multiple-image-picker" library in your react native project. Both the libraries working same.

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!
