### ISSUE TITLE
openPicker doesn't return a response when I press the "done" button without making any changes to the selectedAssets

### ISSUE THREAD

**Issue by YubinKim16** [baronha/react-native-multiple-image-picker#93]
My app asks users to upload at least 10 photos and if they don't, it triggers an alert with a button that redirects the user to the photo gallery (retaining the selected photos).

But when the user hits the done button again WITHOUT making any changes to the list of selected photos, then openPicker doesn't get triggered at all (the function doesn't return anything, not even null). So, the app fails to trigger the alert button (it should be triggered because the user still hasn't selected 10 photos).

Could someone please help me out?

**Comment by baronha** [comment]
Handle your case in `js code`. Because this library only considers the maximum condition when selecting

**Comment by krisnapy** [comment]
I’m facing the same issue. When I click 'Done' without making any changes in the picker, it doesn’t return anything and stays stuck in the `openPicker` function. Is there a fix or workaround for this?
