### ISSUE TITLE
Read memory card access denied after taking permission from user

### ISSUE THREAD

**Issue by kush4999** [baronha/react-native-multiple-image-picker#94]
I'm getting error Read memory card access denied in "baronha/react-native-multiple-image-picker". I already taken run time permission from users still getting same any one have any solution?

//taking permission
![image1](https://user-images.githubusercontent.com/62102982/221106681-d325b015-4808-47dc-9cb7-46bc4b81ea81.jpg)

//permission granted screenshot in app settings
![image2](https://user-images.githubusercontent.com/62102982/221106790-23cb1ad5-f155-4f12-b9dc-e3f1bc034029.jpg)

//issue faced
![issue_image](https://user-images.githubusercontent.com/62102982/221106870-a20543bb-2629-4930-87e1-f112483d45ca.jpg)

**Comment by kush4999** [comment]
Describe my issue

I'm getting error Read memory card access denied in "baronha/react-native-multiple-image-picker". I already taken run time permission from users still getting same any one have any solution?

//taking permission
![image1](https://user-images.githubusercontent.com/62102982/221106681-d325b015-4808-47dc-9cb7-46bc4b81ea81.jpg)

//permission granted screenshot in app settings
![image2](https://user-images.githubusercontent.com/62102982/221106790-23cb1ad5-f155-4f12-b9dc-e3f1bc034029.jpg)

//issue faced
![issue_image](https://user-images.githubusercontent.com/62102982/221106870-a20543bb-2629-4930-87e1-f112483d45ca.jpg)

**Comment by KyumKyum** [comment]
I think this happens for android devices higher than version 13. This package only requires READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE, but we need different permission to access media for version 13 or higher, which is READ_MEDIA_IMAGES. (https://developer.android.com/about/versions/13/behavior-changes-13)

I'm currently finding a way to make this package also works for permission READ_MEDIA_IMAGES and READ_MEDIA_VIDEO. I'll update my comment if I found my way to resolve this problem. :)

**Comment by uaround-jisu** [comment]
업데이트 된게 있으면 알려주시기 바랍니다

**Comment by kush4999** [comment]
Uninstall ""baronha/react-native-multiple-image-picker"" library from the project install "@ko-developerhong/react-native-multiple-image-picker" library in your react native project. Both the libraries working same.
