### ISSUE TITLE
Execution failed for task ':baronha_react-native-multiple-image-picker:compileDebugKotlin'

### ISSUE THREAD

**Issue by duongbui234** [baronha/react-native-multiple-image-picker#96]
I also got the same error like[ issue 44 ](https://github.com/baronha/react-native-multiple-image-picker/issues/44).I downgraded the version to ver11 but still no success
![image](https://user-images.githubusercontent.com/67871183/223989829-dac19b9d-2ecb-463e-9603-82e5c3b6811b.png)
"@baronha/react-native-multiple-image-picker": "^0.4.8",
"react-native": "0.66.0",

**Comment by baronha** [comment]
Please check the new version ( The current version is `ver.1.0.0` )!

**Comment by Martyneris** [comment]
I have this exact same issue with `react-native: 0.73.2` and `@baronha/react-native-multiple-image-picker": "^1.1.6"`

**Comment by Flocurry** [comment]
I this issue too

"@baronha/react-native-multiple-image-picker": "^1.1.6",
"react-native": "0.73.2",
