### ISSUE TITLE
Cannot open picker on version 1.0.0

### ISSUE THREAD

**Issue by huyth-2224** [baronha/react-native-multiple-image-picker#98]
I create sample to check version 1.0.0. But cannot open picker in iOS and Android.

```
 const handleButtonPress = async () => {
    MultipleImagePicker.openPicker();
  };
```
On terminal
```
Possible Unhandled Promise Rejection (id: 2):
TypeError: undefined is not an object (evaluating '_reactNativeMultipleImagePicker.default.openPicker')
```

Package.json
`  "@baronha/react-native-multiple-image-picker": "^1.0.0",`

**Comment by AmitHBhagat** [comment]
Please update "Usage" section on "https://www.npmjs.com/package/@baronha/react-native-multiple-image-picker/v/1.0.0?activeTab=readme" with `import { openPicker } from '@baronha/react-native-multiple-image-picker';`
